//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Chiro.Gap.Workers.Test.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("yvonne")]
        public string TestGav1 {
            get {
                return ((string)(this["TestGav1"]));
            }
            set {
                this["TestGav1"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public int TestAdNummer {
            get {
                return ((int)(this["TestAdNummer"]));
            }
            set {
                this["TestAdNummer"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("317")]
        public int GroepID {
            get {
                return ((int)(this["GroepID"]));
            }
            set {
                this["GroepID"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("TestKookies")]
        public string CategorieNaam {
            get {
                return ((string)(this["CategorieNaam"]));
            }
            set {
                this["CategorieNaam"] = value;
            }
        }
    }
}
