//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CgWeb.PersonenServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasisEntity", Namespace="http://schemas.datacontract.org/2004/07/CgDal")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CgWeb.PersonenServiceReference.PersoonsAdres))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CgWeb.PersonenServiceReference.Persoon))]
    public partial class BasisEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CgWeb.PersonenServiceReference.EntityStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CgWeb.PersonenServiceReference.EntityStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersoonsAdres", Namespace="http://schemas.datacontract.org/2004/07/CgDal")]
    [System.SerializableAttribute()]
    public partial class PersoonsAdres : CgWeb.PersonenServiceReference.BasisEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsStandaardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpmerkingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersoonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdresIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdresTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CgWeb.PersonenServiceReference.Binary VersieField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsStandaard {
            get {
                return this.IsStandaardField;
            }
            set {
                if ((this.IsStandaardField.Equals(value) != true)) {
                    this.IsStandaardField = value;
                    this.RaisePropertyChanged("IsStandaard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opmerking {
            get {
                return this.OpmerkingField;
            }
            set {
                if ((object.ReferenceEquals(this.OpmerkingField, value) != true)) {
                    this.OpmerkingField = value;
                    this.RaisePropertyChanged("Opmerking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersoonID {
            get {
                return this.PersoonIDField;
            }
            set {
                if ((this.PersoonIDField.Equals(value) != true)) {
                    this.PersoonIDField = value;
                    this.RaisePropertyChanged("PersoonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int AdresID {
            get {
                return this.AdresIDField;
            }
            set {
                if ((this.AdresIDField.Equals(value) != true)) {
                    this.AdresIDField = value;
                    this.RaisePropertyChanged("AdresID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int AdresTypeID {
            get {
                return this.AdresTypeIDField;
            }
            set {
                if ((this.AdresTypeIDField.Equals(value) != true)) {
                    this.AdresTypeIDField = value;
                    this.RaisePropertyChanged("AdresTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public CgWeb.PersonenServiceReference.Binary Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persoon", Namespace="http://schemas.datacontract.org/2004/07/CgDal")]
    [System.SerializableAttribute()]
    public partial class Persoon : CgWeb.PersonenServiceReference.BasisEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AdNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoorNaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> GeboorteDatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GeslachtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChiroLeefTijdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SterfDatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersoonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CgWeb.PersonenServiceReference.Binary VersieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CgWeb.PersonenServiceReference.PersoonsAdres[] PersoonsAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CgWeb.PersonenServiceReference.GelieerdePersoon[] GelieerdePersoonsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AdNummer {
            get {
                return this.AdNummerField;
            }
            set {
                if ((this.AdNummerField.Equals(value) != true)) {
                    this.AdNummerField = value;
                    this.RaisePropertyChanged("AdNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoorNaam {
            get {
                return this.VoorNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.VoorNaamField, value) != true)) {
                    this.VoorNaamField = value;
                    this.RaisePropertyChanged("VoorNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> GeboorteDatum {
            get {
                return this.GeboorteDatumField;
            }
            set {
                if ((this.GeboorteDatumField.Equals(value) != true)) {
                    this.GeboorteDatumField = value;
                    this.RaisePropertyChanged("GeboorteDatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Geslacht {
            get {
                return this.GeslachtField;
            }
            set {
                if ((this.GeslachtField.Equals(value) != true)) {
                    this.GeslachtField = value;
                    this.RaisePropertyChanged("Geslacht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ChiroLeefTijd {
            get {
                return this.ChiroLeefTijdField;
            }
            set {
                if ((this.ChiroLeefTijdField.Equals(value) != true)) {
                    this.ChiroLeefTijdField = value;
                    this.RaisePropertyChanged("ChiroLeefTijd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<System.DateTime> SterfDatum {
            get {
                return this.SterfDatumField;
            }
            set {
                if ((this.SterfDatumField.Equals(value) != true)) {
                    this.SterfDatumField = value;
                    this.RaisePropertyChanged("SterfDatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.Guid> Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((this.GuidField.Equals(value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int PersoonID {
            get {
                return this.PersoonIDField;
            }
            set {
                if ((this.PersoonIDField.Equals(value) != true)) {
                    this.PersoonIDField = value;
                    this.RaisePropertyChanged("PersoonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public CgWeb.PersonenServiceReference.Binary Versie {
            get {
                return this.VersieField;
            }
            set {
                if ((object.ReferenceEquals(this.VersieField, value) != true)) {
                    this.VersieField = value;
                    this.RaisePropertyChanged("Versie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public CgWeb.PersonenServiceReference.PersoonsAdres[] PersoonsAdres {
            get {
                return this.PersoonsAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.PersoonsAdresField, value) != true)) {
                    this.PersoonsAdresField = value;
                    this.RaisePropertyChanged("PersoonsAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public CgWeb.PersonenServiceReference.GelieerdePersoon[] GelieerdePersoons {
            get {
                return this.GelieerdePersoonsField;
            }
            set {
                if ((object.ReferenceEquals(this.GelieerdePersoonsField, value) != true)) {
                    this.GelieerdePersoonsField = value;
                    this.RaisePropertyChanged("GelieerdePersoons");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityStatus", Namespace="http://schemas.datacontract.org/2004/07/CgDal")]
    public enum EntityStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Geen = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nieuw = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gewijzigd = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verwijderd = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GelieerdePersoon", Namespace="http://schemas.datacontract.org/2004/07/CgDal")]
    [System.SerializableAttribute()]
    public partial class GelieerdePersoon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroepIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersoonIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroepID {
            get {
                return this.GroepIDField;
            }
            set {
                if ((this.GroepIDField.Equals(value) != true)) {
                    this.GroepIDField = value;
                    this.RaisePropertyChanged("GroepID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersoonID {
            get {
                return this.PersoonIDField;
            }
            set {
                if ((this.PersoonIDField.Equals(value) != true)) {
                    this.PersoonIDField = value;
                    this.RaisePropertyChanged("PersoonID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vPersoonsInfo", Namespace="http://schemas.datacontract.org/2004/07/CgDal")]
    [System.SerializableAttribute()]
    public partial class vPersoonsInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroepIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersoonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoorNaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategorieenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StraatNaamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HuisNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubGemeenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> GeboorteDatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EindeInstapPeriodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> NonActiefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoonNummerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroepID {
            get {
                return this.GroepIDField;
            }
            set {
                if ((this.GroepIDField.Equals(value) != true)) {
                    this.GroepIDField = value;
                    this.RaisePropertyChanged("GroepID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersoonID {
            get {
                return this.PersoonIDField;
            }
            set {
                if ((this.PersoonIDField.Equals(value) != true)) {
                    this.PersoonIDField = value;
                    this.RaisePropertyChanged("PersoonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoorNaam {
            get {
                return this.VoorNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.VoorNaamField, value) != true)) {
                    this.VoorNaamField = value;
                    this.RaisePropertyChanged("VoorNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Categorieen {
            get {
                return this.CategorieenField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorieenField, value) != true)) {
                    this.CategorieenField = value;
                    this.RaisePropertyChanged("Categorieen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string StraatNaam {
            get {
                return this.StraatNaamField;
            }
            set {
                if ((object.ReferenceEquals(this.StraatNaamField, value) != true)) {
                    this.StraatNaamField = value;
                    this.RaisePropertyChanged("StraatNaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> HuisNr {
            get {
                return this.HuisNrField;
            }
            set {
                if ((this.HuisNrField.Equals(value) != true)) {
                    this.HuisNrField = value;
                    this.RaisePropertyChanged("HuisNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Bus {
            get {
                return this.BusField;
            }
            set {
                if ((object.ReferenceEquals(this.BusField, value) != true)) {
                    this.BusField = value;
                    this.RaisePropertyChanged("Bus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int PostNr {
            get {
                return this.PostNrField;
            }
            set {
                if ((this.PostNrField.Equals(value) != true)) {
                    this.PostNrField = value;
                    this.RaisePropertyChanged("PostNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string SubGemeente {
            get {
                return this.SubGemeenteField;
            }
            set {
                if ((object.ReferenceEquals(this.SubGemeenteField, value) != true)) {
                    this.SubGemeenteField = value;
                    this.RaisePropertyChanged("SubGemeente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<System.DateTime> GeboorteDatum {
            get {
                return this.GeboorteDatumField;
            }
            set {
                if ((this.GeboorteDatumField.Equals(value) != true)) {
                    this.GeboorteDatumField = value;
                    this.RaisePropertyChanged("GeboorteDatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<System.DateTime> EindeInstapPeriode {
            get {
                return this.EindeInstapPeriodeField;
            }
            set {
                if ((this.EindeInstapPeriodeField.Equals(value) != true)) {
                    this.EindeInstapPeriodeField = value;
                    this.RaisePropertyChanged("EindeInstapPeriode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> NonActief {
            get {
                return this.NonActiefField;
            }
            set {
                if ((this.NonActiefField.Equals(value) != true)) {
                    this.NonActiefField = value;
                    this.RaisePropertyChanged("NonActief");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string TelefoonNummer {
            get {
                return this.TelefoonNummerField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoonNummerField, value) != true)) {
                    this.TelefoonNummerField = value;
                    this.RaisePropertyChanged("TelefoonNummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonenServiceReference.IPersonenService")]
    public interface IPersonenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/Hallo", ReplyAction="http://tempuri.org/IPersonenService/HalloResponse")]
        string Hallo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/PersoonGet", ReplyAction="http://tempuri.org/IPersonenService/PersoonGetResponse")]
        CgWeb.PersonenServiceReference.Persoon PersoonGet(int persoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/PersoonMetAdressenGet", ReplyAction="http://tempuri.org/IPersonenService/PersoonMetAdressenGetResponse")]
        CgWeb.PersonenServiceReference.Persoon PersoonMetAdressenGet(int PersoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/GelieerdePersonenInfoGet", ReplyAction="http://tempuri.org/IPersonenService/GelieerdePersonenInfoGetResponse")]
        CgWeb.PersonenServiceReference.vPersoonsInfo[] GelieerdePersonenInfoGet(int GroepID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/PersoonUpdaten", ReplyAction="http://tempuri.org/IPersonenService/PersoonUpdatenResponse")]
        int PersoonUpdaten(CgWeb.PersonenServiceReference.Persoon persoon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPersonenServiceChannel : CgWeb.PersonenServiceReference.IPersonenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PersonenServiceClient : System.ServiceModel.ClientBase<CgWeb.PersonenServiceReference.IPersonenService>, CgWeb.PersonenServiceReference.IPersonenService {
        
        public PersonenServiceClient() {
        }
        
        public PersonenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hallo() {
            return base.Channel.Hallo();
        }
        
        public CgWeb.PersonenServiceReference.Persoon PersoonGet(int persoonID) {
            return base.Channel.PersoonGet(persoonID);
        }
        
        public CgWeb.PersonenServiceReference.Persoon PersoonMetAdressenGet(int PersoonID) {
            return base.Channel.PersoonMetAdressenGet(PersoonID);
        }
        
        public CgWeb.PersonenServiceReference.vPersoonsInfo[] GelieerdePersonenInfoGet(int GroepID) {
            return base.Channel.GelieerdePersonenInfoGet(GroepID);
        }
        
        public int PersoonUpdaten(CgWeb.PersonenServiceReference.Persoon persoon) {
            return base.Channel.PersoonUpdaten(persoon);
        }
    }
}
