//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Gap.FixAnomalies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Gap.FixAnomalies.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvragen actieve lidrelaties CiviCRM..
        /// </summary>
        internal static string Opvragen_actieve_lidrelaties_CiviCRM_ {
            get {
                return ResourceManager.GetString("Opvragen_actieve_lidrelaties_CiviCRM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bivakken uit GAP niet (volledig) gevonden in Civi..
        /// </summary>
        internal static string Program_BivakAangiftesFixen__0__bivakken_uit_GAP_niet_gevonden_in_Civi_ {
            get {
                return ResourceManager.GetString("Program_BivakAangiftesFixen__0__bivakken_uit_GAP_niet_gevonden_in_Civi_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophalen volledige bivakaangiftes uit CiviCRM..
        /// </summary>
        internal static string Program_BivakAangiftesFixen_Ophalen_volledige_bivakaangiftes_uit_CiviCRM_ {
            get {
                return ResourceManager.GetString("Program_BivakAangiftesFixen_Ophalen_volledige_bivakaangiftes_uit_CiviCRM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volledige bivakaangiftes ophalen uit het GAP..
        /// </summary>
        internal static string Program_BivakAangiftesFixen_Volledige_bivakaangiftes_ophalen_uit_het_GAP_ {
            get {
                return ResourceManager.GetString("Program_BivakAangiftesFixen_Volledige_bivakaangiftes_ophalen_uit_het_GAP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actieve Dubbelpuntabonnementen ophalen uit CiviCRM..
        /// </summary>
        internal static string Program_DubbelpuntFixen_Actieve_Dubbelpuntabonnementen_ophalen_uit_CiviCRM_ {
            get {
                return ResourceManager.GetString("Program_DubbelpuntFixen_Actieve_Dubbelpuntabonnementen_ophalen_uit_CiviCRM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitschrijven doen we nog maar niet; het zou kunnen dat er mensen niet in gap waren gevonden omdat er nog geen AD-nummers terug kwamen..
        /// </summary>
        internal static string Program_LidRelatiesFixen_Uitschrijven_doen_we_nog_maar_niet__het_zou_kunnen_dat_er_mensen_niet_in_gap_waren_gevonden_omdat_er_nog_geen_AD_nummers_terug_kwamen_ {
            get {
                return ResourceManager.GetString("Program_LidRelatiesFixen_Uitschrijven_doen_we_nog_maar_niet__het_zou_kunnen_dat_e" +
                        "r_mensen_niet_in_gap_waren_gevonden_omdat_er_nog_geen_AD_nummers_terug_kwamen_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} verzekeringen te kort in CiviCRM..
        /// </summary>
        internal static string Program_LoonVerliesFixen__0__verzekeringen_te_kort_in_CiviCRM_ {
            get {
                return ResourceManager.GetString("Program_LoonVerliesFixen__0__verzekeringen_te_kort_in_CiviCRM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofwel zijn er zo geen, ofwel is Zulma op de hoogte..
        /// </summary>
        internal static string Program_LoonVerliesFixen_Ofwel_zijn_er_zo_geen__ofwel_is_Zulma_op_de_hoogte_ {
            get {
                return ResourceManager.GetString("Program_LoonVerliesFixen_Ofwel_zijn_er_zo_geen__ofwel_is_Zulma_op_de_hoogte_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvragen actieve memberships met loonverlies uit CiviCRM..
        /// </summary>
        internal static string Program_LoonVerliesFixen_Opvragen_actieve_memberships_met_loonverlies_uit_CiviCRM_ {
            get {
                return ResourceManager.GetString("Program_LoonVerliesFixen_Opvragen_actieve_memberships_met_loonverlies_uit_CiviCRM" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen waarvoor Kipadmin loonverlies factureerde, maar die niet aangesloten zijn:.
        /// </summary>
        internal static string Program_LoonVerliesFixen_Personen_waarvoor_Kipadmin_loonverlies_factureerde__maar_die_niet_aangesloten_zijn_ {
            get {
                return ResourceManager.GetString("Program_LoonVerliesFixen_Personen_waarvoor_Kipadmin_loonverlies_factureerde__maar" +
                        "_die_niet_aangesloten_zijn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzekeringen loonverlies opvragen uit GAP..
        /// </summary>
        internal static string Program_LoonVerliesFixen_Verzekeringen_loonverlies_opvragen_uit_GAP_ {
            get {
                return ResourceManager.GetString("Program_LoonVerliesFixen_Verzekeringen_loonverlies_opvragen_uit_GAP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} leden uit CiviCRM niet teruggevonden in GAP..
        /// </summary>
        internal static string Program_Main__0__leden_uit_CiviCRM_niet_teruggevonden_in_GAP_ {
            get {
                return ResourceManager.GetString("Program_Main__0__leden_uit_CiviCRM_niet_teruggevonden_in_GAP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} leden uit GAP niet teruggevonden in CiviCRM..
        /// </summary>
        internal static string Program_Main__0__leden_uit_GAP_niet_teruggevonden_in_CiviCRM_ {
            get {
                return ResourceManager.GetString("Program_Main__0__leden_uit_GAP_niet_teruggevonden_in_CiviCRM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat zijn er {0}..
        /// </summary>
        internal static string Program_Main_Dat_zijn_er__0__ {
            get {
                return ResourceManager.GetString("Program_Main_Dat_zijn_er__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druk ENTER..
        /// </summary>
        internal static string Program_Main_Druk_ENTER_ {
            get {
                return ResourceManager.GetString("Program_Main_Druk_ENTER_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteen syncen? .
        /// </summary>
        internal static string Program_Main_Meteen_syncen__ {
            get {
                return ResourceManager.GetString("Program_Main_Meteen_syncen__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvragen actieve leden in Gap..
        /// </summary>
        internal static string Program_Main_Opvragen_actieve_leden_GAP__ {
            get {
                return ResourceManager.GetString("Program_Main_Opvragen_actieve_leden_GAP__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opvragen actieve lidrelaties CiviCRM..
        /// </summary>
        internal static string Program_Main_Opvragen_actieve_lidrelaties_CiviCRM_ {
            get {
                return ResourceManager.GetString("Program_Main_Opvragen_actieve_lidrelaties_CiviCRM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitschrijven uit Civi? .
        /// </summary>
        internal static string Program_Main_Uitschrijven_uit_Civi__ {
            get {
                return ResourceManager.GetString("Program_Main_Uitschrijven_uit_Civi__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzoeken bivakken in GAP die niet volledig in Civi zitten..
        /// </summary>
        internal static string Program_OntbrekendInCiviZoeken_Opzoeken_bivakken_in_GAP_die_niet_volledig_in_Civi_zitten_ {
            get {
                return ResourceManager.GetString("Program_OntbrekendInCiviZoeken_Opzoeken_bivakken_in_GAP_die_niet_volledig_in_Civi" +
                        "_zitten_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzoeken leden in GAP maar niet in CiviCRM..
        /// </summary>
        internal static string Program_OntbrekendInCiviZoeken_Opzoeken_leden_in_GAP_maar_niet_in_CiviCRM_ {
            get {
                return ResourceManager.GetString("Program_OntbrekendInCiviZoeken_Opzoeken_leden_in_GAP_maar_niet_in_CiviCRM_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzoeken leden in CiviCRM maar niet in GAP..
        /// </summary>
        internal static string Program_TeVeelInCiviZoeken_Opzoeken_leden_in_CiviCRM_maar_niet_in_GAP_ {
            get {
                return ResourceManager.GetString("Program_TeVeelInCiviZoeken_Opzoeken_leden_in_CiviCRM_maar_niet_in_GAP_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: {0} [-a|-b|-d|-l]
        ///    -a  kijkt alles na
        ///    -b  kijkt bivakken na
        ///    -d  kijkt dubbelpuntabonnementen na
        ///    -l  kijkt leden na.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
