//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Cdf.Mailer.MailServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BerichtStatus", Namespace="http://intranet/MailService")]
    [System.SerializableAttribute()]
    public partial class BerichtStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsVerstuurdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogBoodschapField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsVerstuurd {
            get {
                return this.IsVerstuurdField;
            }
            set {
                if ((this.IsVerstuurdField.Equals(value) != true)) {
                    this.IsVerstuurdField = value;
                    this.RaisePropertyChanged("IsVerstuurd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LogBoodschap {
            get {
                return this.LogBoodschapField;
            }
            set {
                if ((object.ReferenceEquals(this.LogBoodschapField, value) != true)) {
                    this.LogBoodschapField = value;
                    this.RaisePropertyChanged("LogBoodschap");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intranet/MailService", ConfigurationName="MailServiceReference.MailServiceSoap")]
    public interface MailServiceSoap {
        
        // CODEGEN: Generating message contract since element name VanNaamParam from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurMail", ReplyAction="*")]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailResponse VerstuurMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailRequest request);
        
        // CODEGEN: Generating message contract since element name VoorAdresParam from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurGapMail", ReplyAction="*")]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailResponse VerstuurGapMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailRequest request);
        
        // CODEGEN: Generating message contract since element name VoorAdresParam from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurSomMail", ReplyAction="*")]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailResponse VerstuurSomMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailRequest request);
        
        // CODEGEN: Generating message contract since element name OverParam from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurLogMail", ReplyAction="*")]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailResponse VerstuurLogMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailRequest request);
        
        // CODEGEN: Generating message contract since element name OverParam from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/LogMailVersturen", ReplyAction="*")]
        Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenResponse LogMailVersturen(Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenRequest request);
        
        // CODEGEN: Generating message contract since element name SoortMeldingParam from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurCustomLogMail", ReplyAction="*")]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailResponse VerstuurCustomLogMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailRequestBody Body;
        
        public VerstuurMailRequest() {
        }
        
        public VerstuurMailRequest(Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VanNaamParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VoorAdresParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OverParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BoodschapParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ApplicatieNaamParam;
        
        public VerstuurMailRequestBody() {
        }
        
        public VerstuurMailRequestBody(string VanNaamParam, string VoorAdresParam, string OverParam, string BoodschapParam, string ApplicatieNaamParam) {
            this.VanNaamParam = VanNaamParam;
            this.VoorAdresParam = VoorAdresParam;
            this.OverParam = OverParam;
            this.BoodschapParam = BoodschapParam;
            this.ApplicatieNaamParam = ApplicatieNaamParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailResponseBody Body;
        
        public VerstuurMailResponse() {
        }
        
        public VerstuurMailResponse(Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurMailResult;
        
        public VerstuurMailResponseBody() {
        }
        
        public VerstuurMailResponseBody(Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurMailResult) {
            this.VerstuurMailResult = VerstuurMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurGapMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurGapMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailRequestBody Body;
        
        public VerstuurGapMailRequest() {
        }
        
        public VerstuurGapMailRequest(Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurGapMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VoorAdresParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OverParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BoodschapParam;
        
        public VerstuurGapMailRequestBody() {
        }
        
        public VerstuurGapMailRequestBody(string VoorAdresParam, string OverParam, string BoodschapParam) {
            this.VoorAdresParam = VoorAdresParam;
            this.OverParam = OverParam;
            this.BoodschapParam = BoodschapParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurGapMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurGapMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailResponseBody Body;
        
        public VerstuurGapMailResponse() {
        }
        
        public VerstuurGapMailResponse(Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurGapMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurGapMailResult;
        
        public VerstuurGapMailResponseBody() {
        }
        
        public VerstuurGapMailResponseBody(Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurGapMailResult) {
            this.VerstuurGapMailResult = VerstuurGapMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurSomMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurSomMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailRequestBody Body;
        
        public VerstuurSomMailRequest() {
        }
        
        public VerstuurSomMailRequest(Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurSomMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VoorAdresParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OverParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BoodschapParam;
        
        public VerstuurSomMailRequestBody() {
        }
        
        public VerstuurSomMailRequestBody(string VoorAdresParam, string OverParam, string BoodschapParam) {
            this.VoorAdresParam = VoorAdresParam;
            this.OverParam = OverParam;
            this.BoodschapParam = BoodschapParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurSomMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurSomMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailResponseBody Body;
        
        public VerstuurSomMailResponse() {
        }
        
        public VerstuurSomMailResponse(Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurSomMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurSomMailResult;
        
        public VerstuurSomMailResponseBody() {
        }
        
        public VerstuurSomMailResponseBody(Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurSomMailResult) {
            this.VerstuurSomMailResult = VerstuurSomMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurLogMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurLogMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailRequestBody Body;
        
        public VerstuurLogMailRequest() {
        }
        
        public VerstuurLogMailRequest(Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurLogMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OverParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BoodschapParam;
        
        public VerstuurLogMailRequestBody() {
        }
        
        public VerstuurLogMailRequestBody(string OverParam, string BoodschapParam) {
            this.OverParam = OverParam;
            this.BoodschapParam = BoodschapParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurLogMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurLogMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailResponseBody Body;
        
        public VerstuurLogMailResponse() {
        }
        
        public VerstuurLogMailResponse(Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurLogMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurLogMailResult;
        
        public VerstuurLogMailResponseBody() {
        }
        
        public VerstuurLogMailResponseBody(Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurLogMailResult) {
            this.VerstuurLogMailResult = VerstuurLogMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogMailVersturenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogMailVersturen", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenRequestBody Body;
        
        public LogMailVersturenRequest() {
        }
        
        public LogMailVersturenRequest(Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class LogMailVersturenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OverParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BoodschapParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool IsFoutlogParam;
        
        public LogMailVersturenRequestBody() {
        }
        
        public LogMailVersturenRequestBody(string OverParam, string BoodschapParam, bool IsFoutlogParam) {
            this.OverParam = OverParam;
            this.BoodschapParam = BoodschapParam;
            this.IsFoutlogParam = IsFoutlogParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogMailVersturenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogMailVersturenResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenResponseBody Body;
        
        public LogMailVersturenResponse() {
        }
        
        public LogMailVersturenResponse(Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class LogMailVersturenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus LogMailVersturenResult;
        
        public LogMailVersturenResponseBody() {
        }
        
        public LogMailVersturenResponseBody(Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus LogMailVersturenResult) {
            this.LogMailVersturenResult = LogMailVersturenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurCustomLogMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurCustomLogMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailRequestBody Body;
        
        public VerstuurCustomLogMailRequest() {
        }
        
        public VerstuurCustomLogMailRequest(Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurCustomLogMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoortMeldingParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OverParam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BoodschapParam;
        
        public VerstuurCustomLogMailRequestBody() {
        }
        
        public VerstuurCustomLogMailRequestBody(string SoortMeldingParam, string OverParam, string BoodschapParam) {
            this.SoortMeldingParam = SoortMeldingParam;
            this.OverParam = OverParam;
            this.BoodschapParam = BoodschapParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurCustomLogMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurCustomLogMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailResponseBody Body;
        
        public VerstuurCustomLogMailResponse() {
        }
        
        public VerstuurCustomLogMailResponse(Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurCustomLogMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurCustomLogMailResult;
        
        public VerstuurCustomLogMailResponseBody() {
        }
        
        public VerstuurCustomLogMailResponseBody(Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurCustomLogMailResult) {
            this.VerstuurCustomLogMailResult = VerstuurCustomLogMailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailServiceSoapChannel : Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceSoapClient : System.ServiceModel.ClientBase<Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap>, Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap {
        
        public MailServiceSoapClient() {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailResponse Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap.VerstuurMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailRequest request) {
            return base.Channel.VerstuurMail(request);
        }
        
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurMail(string VanNaamParam, string VoorAdresParam, string OverParam, string BoodschapParam, string ApplicatieNaamParam) {
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailRequest inValue = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailRequest();
            inValue.Body = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailRequestBody();
            inValue.Body.VanNaamParam = VanNaamParam;
            inValue.Body.VoorAdresParam = VoorAdresParam;
            inValue.Body.OverParam = OverParam;
            inValue.Body.BoodschapParam = BoodschapParam;
            inValue.Body.ApplicatieNaamParam = ApplicatieNaamParam;
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurMailResponse retVal = ((Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap)(this)).VerstuurMail(inValue);
            return retVal.Body.VerstuurMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailResponse Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap.VerstuurGapMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailRequest request) {
            return base.Channel.VerstuurGapMail(request);
        }
        
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurGapMail(string VoorAdresParam, string OverParam, string BoodschapParam) {
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailRequest inValue = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailRequest();
            inValue.Body = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailRequestBody();
            inValue.Body.VoorAdresParam = VoorAdresParam;
            inValue.Body.OverParam = OverParam;
            inValue.Body.BoodschapParam = BoodschapParam;
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurGapMailResponse retVal = ((Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap)(this)).VerstuurGapMail(inValue);
            return retVal.Body.VerstuurGapMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailResponse Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap.VerstuurSomMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailRequest request) {
            return base.Channel.VerstuurSomMail(request);
        }
        
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurSomMail(string VoorAdresParam, string OverParam, string BoodschapParam) {
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailRequest inValue = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailRequest();
            inValue.Body = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailRequestBody();
            inValue.Body.VoorAdresParam = VoorAdresParam;
            inValue.Body.OverParam = OverParam;
            inValue.Body.BoodschapParam = BoodschapParam;
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurSomMailResponse retVal = ((Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap)(this)).VerstuurSomMail(inValue);
            return retVal.Body.VerstuurSomMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailResponse Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap.VerstuurLogMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailRequest request) {
            return base.Channel.VerstuurLogMail(request);
        }
        
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurLogMail(string OverParam, string BoodschapParam) {
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailRequest inValue = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailRequest();
            inValue.Body = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailRequestBody();
            inValue.Body.OverParam = OverParam;
            inValue.Body.BoodschapParam = BoodschapParam;
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurLogMailResponse retVal = ((Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap)(this)).VerstuurLogMail(inValue);
            return retVal.Body.VerstuurLogMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenResponse Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap.LogMailVersturen(Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenRequest request) {
            return base.Channel.LogMailVersturen(request);
        }
        
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus LogMailVersturen(string OverParam, string BoodschapParam, bool IsFoutlogParam) {
            Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenRequest inValue = new Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenRequest();
            inValue.Body = new Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenRequestBody();
            inValue.Body.OverParam = OverParam;
            inValue.Body.BoodschapParam = BoodschapParam;
            inValue.Body.IsFoutlogParam = IsFoutlogParam;
            Chiro.Cdf.Mailer.MailServiceReference.LogMailVersturenResponse retVal = ((Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap)(this)).LogMailVersturen(inValue);
            return retVal.Body.LogMailVersturenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailResponse Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap.VerstuurCustomLogMail(Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailRequest request) {
            return base.Channel.VerstuurCustomLogMail(request);
        }
        
        public Chiro.Cdf.Mailer.MailServiceReference.BerichtStatus VerstuurCustomLogMail(string SoortMeldingParam, string OverParam, string BoodschapParam) {
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailRequest inValue = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailRequest();
            inValue.Body = new Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailRequestBody();
            inValue.Body.SoortMeldingParam = SoortMeldingParam;
            inValue.Body.OverParam = OverParam;
            inValue.Body.BoodschapParam = BoodschapParam;
            Chiro.Cdf.Mailer.MailServiceReference.VerstuurCustomLogMailResponse retVal = ((Chiro.Cdf.Mailer.MailServiceReference.MailServiceSoap)(this)).VerstuurCustomLogMail(inValue);
            return retVal.Body.VerstuurCustomLogMailResult;
        }
    }
}
