//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICursusService")]
    public interface ICursusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursusService/CursusMaken", ReplyAction="http://tempuri.org/ICursusService/CursusMakenResponse")]
        int CursusMaken(string naam, System.DateTime startDatum, System.DateTime stopDatum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursusService/DeelnemerInschrijven", ReplyAction="http://tempuri.org/ICursusService/DeelnemerInschrijvenResponse")]
        int DeelnemerInschrijven(int cursusID, string deelnemerNaam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursusService/DeelnemersOphalen", ReplyAction="http://tempuri.org/ICursusService/DeelnemersOphalenResponse")]
        string[] DeelnemersOphalen(int cursusID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursusService/Hallo", ReplyAction="http://tempuri.org/ICursusService/HalloResponse")]
        string Hallo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursusService/DeelnemerVerwijderen", ReplyAction="http://tempuri.org/ICursusService/DeelnemerVerwijderenResponse")]
        void DeelnemerVerwijderen(int cursusID, string naam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursusServiceChannel : Client.ServiceReference1.ICursusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursusServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.ICursusService>, Client.ServiceReference1.ICursusService {
        
        public CursusServiceClient() {
        }
        
        public CursusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CursusMaken(string naam, System.DateTime startDatum, System.DateTime stopDatum) {
            return base.Channel.CursusMaken(naam, startDatum, stopDatum);
        }
        
        public int DeelnemerInschrijven(int cursusID, string deelnemerNaam) {
            return base.Channel.DeelnemerInschrijven(cursusID, deelnemerNaam);
        }
        
        public string[] DeelnemersOphalen(int cursusID) {
            return base.Channel.DeelnemersOphalen(cursusID);
        }
        
        public string Hallo() {
            return base.Channel.Hallo();
        }
        
        public void DeelnemerVerwijderen(int cursusID, string naam) {
            base.Channel.DeelnemerVerwijderen(cursusID, naam);
        }
    }
}
