//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cg2.Services.Test.GelieerdePersonenServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GelieerdePersonenServiceReference.IGelieerdePersonenService")]
    public interface IGelieerdePersonenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/PaginaOphalen", ReplyAction="http://tempuri.org/IGelieerdePersonenService/PaginaOphalenResponse")]
        Cg2.Orm.GelieerdePersoon[] PaginaOphalen(out int aantalOpgehaald, int groepID, int pagina, int paginaGrootte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/DetailsOphalen", ReplyAction="http://tempuri.org/IGelieerdePersonenService/DetailsOphalenResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cg2.Orm.ChiroGroep))]
        Cg2.Orm.GelieerdePersoon DetailsOphalen(int gelieerdePersoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/Bewaren", ReplyAction="http://tempuri.org/IGelieerdePersonenService/BewarenResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cg2.Orm.ChiroGroep))]
        void Bewaren(Cg2.Orm.GelieerdePersoon persoon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IGelieerdePersonenServiceChannel : Cg2.Services.Test.GelieerdePersonenServiceReference.IGelieerdePersonenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GelieerdePersonenServiceClient : System.ServiceModel.ClientBase<Cg2.Services.Test.GelieerdePersonenServiceReference.IGelieerdePersonenService>, Cg2.Services.Test.GelieerdePersonenServiceReference.IGelieerdePersonenService {
        
        public GelieerdePersonenServiceClient() {
        }
        
        public GelieerdePersonenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GelieerdePersonenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GelieerdePersonenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GelieerdePersonenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cg2.Orm.GelieerdePersoon[] PaginaOphalen(out int aantalOpgehaald, int groepID, int pagina, int paginaGrootte) {
            return base.Channel.PaginaOphalen(out aantalOpgehaald, groepID, pagina, paginaGrootte);
        }
        
        public Cg2.Orm.GelieerdePersoon DetailsOphalen(int gelieerdePersoonID) {
            return base.Channel.DetailsOphalen(gelieerdePersoonID);
        }
        
        public void Bewaren(Cg2.Orm.GelieerdePersoon persoon) {
            base.Channel.Bewaren(persoon);
        }
    }
}
