image: mono:4.4.2

stages:
  - build
  - test
  - deploy

# geen idee wat dit is:
cache:
  key: ${CI_BUILD_REF_NAME}

update dev:
  stage: build
  only:
    - dev
  script:
    - cd /builds/gap/gap/Solution
    - git submodule init
    - git submodule update
    - nuget restore
    - xbuild Cg2Solution.sln
