image: gitlab.chiro.be:5443/overig/containers:gap

stages:
# We bouwen eerst alles uit 'tools', en dan Cg2Solution. Want dat
# kan niet parallel, zie #5668.
  - build tools
  - build gap
  - test
  - deploy

# wat die cache is, weet ik niet precies. Ik hoop dat daarmee de gebuilde DLL's
# van de build stage ook beschikbaar zouden zijn voor de test stage.
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - Solution
    - tools

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build loginservice:
  stage: build tools
  only:
    - dev
    - staging
    - master
  script:
    - cd /builds/gap/gap/tools/Chiro.LoginService
    - nuget restore
    - xbuild LoginService.sln

build civisync:
  stage: build tools
  only:
    - dev
    - staging
    - master
  script:
    - cd /builds/gap/gap/tools/Chiro.CiviSync
    - nuget restore
    - xbuild Chiro.CiviSync.sln

build gap:
  stage: build gap
  dependencies:
    - build loginservice
    - build civisync
  only:
    - dev
    - staging
    - master
  script:
    - cd /builds/gap/gap/Solution
    - nuget restore
    - xbuild Cg2Solution.sln
    
unit tests loginservice:
  stage: test
  dependencies:
    - build loginservice
  only:
    - dev
    - staging
    - master
  script:
    - cd /builds/gap/gap
    # in principe zou nunit-console tools/Chiro.LoginService/LoginService.sln moeten gaan,
    # maar dat werkt op dit moment nog niet, omdat in de solution files
    # paden met backslashes geseparated zijn, en daar kan nunit-console
    # onder Linux (docker) niet aan uit.
    - nunit-console tools/Chiro.LoginService/Chiro.Ad.Workers.Test/bin/Debug/Chiro.Ad.Workers.Test.dll

unit tests civisync:
  stage: test
  dependencies:
    - build civisync
  only:
    - dev
    - staging
    - master
  script:
    - cd /builds/gap/gap
    # (Alles op 1 lijn, want met newlines kreeg ik het niet goed.)
    - nunit-console tools/Chiro.CiviSync/Chiro.CiviSync.Logic.Test/bin/Debug/Chiro.CiviSync.Logic.Test.dll tools/Chiro.CiviSync/Chiro.CiviSync.Mapping.Test/bin/Debug/Chiro.CiviSync.Mapping.Test.dll tools/Chiro.CiviSync/Chiro.CiviSync.Services.Test/bin/Debug/Chiro.CiviSync.Services.Test.dll tools/Chiro.CiviSync/Chiro.CiviSync.Workers.Test/bin/Debug/Chiro.CiviSync.Workers.Test.dll

unit tests gap:
  stage: test
  dependencies:
    - build gap
  only:
    - dev
    - staging
    - master
  script:
    - cd /builds/gap/gap
    - nunit-console Solution/TestProjecten/Chiro.Gap.Algemeen.Test/bin/Debug/Chiro.Gap.Algemeen.Test.dll Solution/TestProjecten/Chiro.Gap.Maintenance.Test/bin/Debug/Chiro.Gap.Maintenance.Test.dll Solution/TestProjecten/Chiro.Gap.Services.Dev.Test/bin/Debug/Chiro.Gap.Services.Dev.Test.dll Solution/TestProjecten/Chiro.Gap.Services.Test/bin/Debug/Chiro.Gap.Services.Test.dll Solution/TestProjecten/Chiro.Gap.Sync.Test/bin/Debug/Chiro.Gap.Sync.Test.dll Solution/TestProjecten/Chiro.Gap.UpdateSvc.Test/bin/Debug/Chiro.Gap.UpdateSvc.Test.dll Solution/TestProjecten/Chiro.Gap.WebApp.Test/bin/Debug/Chiro.Gap.WebApp.Test.dll Solution/TestProjecten/Chiro.Gap.Workers.Test/bin/Debug/Chiro.Gap.Workers.Test.dll
