//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cg2Services.Tests.PersonenServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonenServiceReference.IPersonenService")]
    public interface IPersonenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/Ophalen", ReplyAction="http://tempuri.org/IPersonenService/OphalenResponse")]
        Cg2.Core.Domain.Persoon Ophalen(int persoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/OphalenMetCommunicatie", ReplyAction="http://tempuri.org/IPersonenService/OphalenMetCommunicatieResponse")]
        Cg2.Core.Domain.Persoon OphalenMetCommunicatie(int persoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/Hallo", ReplyAction="http://tempuri.org/IPersonenService/HalloResponse")]
        string Hallo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPersonenServiceChannel : Cg2Services.Tests.PersonenServiceReference.IPersonenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PersonenServiceClient : System.ServiceModel.ClientBase<Cg2Services.Tests.PersonenServiceReference.IPersonenService>, Cg2Services.Tests.PersonenServiceReference.IPersonenService {
        
        public PersonenServiceClient() {
        }
        
        public PersonenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cg2.Core.Domain.Persoon Ophalen(int persoonID) {
            return base.Channel.Ophalen(persoonID);
        }
        
        public Cg2.Core.Domain.Persoon OphalenMetCommunicatie(int persoonID) {
            return base.Channel.OphalenMetCommunicatie(persoonID);
        }
        
        public string Hallo() {
            return base.Channel.Hallo();
        }
    }
}
