//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApp2.LedenServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LedenServiceReference.ILedenService")]
    public interface ILedenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILedenService/LidMakenEnBewaren", ReplyAction="http://tempuri.org/ILedenService/LidMakenEnBewarenResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cg2.Orm.ChiroGroep))]
        Cg2.Orm.Lid LidMakenEnBewaren(int gelieerdePersoonID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ILedenServiceChannel : MvcWebApp2.LedenServiceReference.ILedenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LedenServiceClient : System.ServiceModel.ClientBase<MvcWebApp2.LedenServiceReference.ILedenService>, MvcWebApp2.LedenServiceReference.ILedenService {
        
        public LedenServiceClient() {
        }
        
        public LedenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LedenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LedenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LedenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cg2.Orm.Lid LidMakenEnBewaren(int gelieerdePersoonID) {
            return base.Channel.LidMakenEnBewaren(gelieerdePersoonID);
        }
    }
}
