//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Gap.InitieleImport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Gap.InitieleImport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0} {1} bus {2}, {3} {4} ({5}).
        /// </summary>
        internal static string AdresInfo {
            get {
                return ResourceManager.GetString("AdresInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         CommType {1}: {2} {0}.
        /// </summary>
        internal static string CommunicatieInfo {
            get {
                return ResourceManager.GetString("CommunicatieInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---&gt; Fout formaat; Communicatievorm genegeerd.
        /// </summary>
        internal static string CommunicatieVormFoutFormaat {
            get {
                return ResourceManager.GetString("CommunicatieVormFoutFormaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent geen GAV..
        /// </summary>
        internal static string GeenGav {
            get {
                return ResourceManager.GetString("GeenGav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroepID: {0}.
        /// </summary>
        internal static string GroepId {
            get {
                return ResourceManager.GetString("GroepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opnieuw aanmaken groep met standaardafdelingsverdeling..
        /// </summary>
        internal static string GroepOpnieuwAanmaken {
            get {
                return ResourceManager.GetString("GroepOpnieuwAanmaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens importeren van {0} - {1} ({2}).
        /// </summary>
        internal static string GroepsInfo {
            get {
                return ResourceManager.GetString("GroepsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEPS: {0} {1} lijkt te hard op {2} {3}..
        /// </summary>
        internal static string LijktTeHardOp {
            get {
                return ResourceManager.GetString("LijktTeHardOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mogelijk dubbel:.
        /// </summary>
        internal static string MogelijkDubbel {
            get {
                return ResourceManager.GetString("MogelijkDubbel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --&gt; Ongeldig adres genegeerd..
        /// </summary>
        internal static string OnbekendAdres {
            get {
                return ResourceManager.GetString("OnbekendAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt met PersoonID {0}, GelieerdePersoonID {1}..
        /// </summary>
        internal static string PersoonAangemaaktAls {
            get {
                return ResourceManager.GetString("PersoonAangemaaktAls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ({4})  {0} {1} - {2:d} {3}.
        /// </summary>
        internal static string PersoonInfo {
            get {
                return ResourceManager.GetString("PersoonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechten toekennen voor {0}..
        /// </summary>
        internal static string RechtenToekennen {
            get {
                return ResourceManager.GetString("RechtenToekennen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geconnecteerd op services als {0}.
        /// </summary>
        internal static string ServiceUser {
            get {
                return ResourceManager.GetString("ServiceUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *************************** TIMEOUT *******************************.
        /// </summary>
        internal static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal aantal personen: {0}.
        /// </summary>
        internal static string TotaalInfo {
            get {
                return ResourceManager.GetString("TotaalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitpakken van &apos;{0}&apos;.
        /// </summary>
        internal static string UitpakkenVan {
            get {
                return ResourceManager.GetString("UitpakkenVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit programma verwacht het stamnummer als 1ste command-line parameter. (Zet het tussen double quotes (&quot;) om problemen met spaties te vermijden..
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groep wordt volledig verwijderd..
        /// </summary>
        internal static string VolledigVerwijderen {
            get {
                return ResourceManager.GetString("VolledigVerwijderen", resourceCulture);
            }
        }
    }
}
