//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Gap.Workers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Gap.Workers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkel het nationaal secretariaat mag AD-nummers wijzigen..
        /// </summary>
        internal static string AdNummerNietWijzigen {
            get {
                return ResourceManager.GetString("AdNummerNietWijzigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een categorie met code &apos;{0}&apos;..
        /// </summary>
        internal static string CategorieBestaatAl {
            get {
                return ResourceManager.GetString("CategorieBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog personen gekoppeld aan deze categorie..
        /// </summary>
        internal static string CategorieNietLeeg {
            get {
                return ResourceManager.GetString("CategorieNietLeeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is geen geldige waarde voor {1}.
        /// </summary>
        internal static string CommunicatieVormValidatieFeedback {
            get {
                return ResourceManager.GetString("CommunicatieVormValidatieFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze persoon is niet gekoppeld aan de groep waarvan je hem/haar lid wil maken..
        /// </summary>
        internal static string FoutiefGroepsWerkJaar {
            get {
                return ResourceManager.GetString("FoutiefGroepsWerkJaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een lid te koppelen aan een functie die niet geldig is voor het gegeven werkjaar..
        /// </summary>
        internal static string FoutiefGroepsWerkJaarFunctie {
            get {
                return ResourceManager.GetString("FoutiefGroepsWerkJaarFunctie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een persoon te koppelen aan een categorie uit een andere groep..
        /// </summary>
        internal static string FoutieveGroepCategorie {
            get {
                return ResourceManager.GetString("FoutieveGroepCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een lid te koppelen aan een categorie uit een andere groep..
        /// </summary>
        internal static string FoutieveGroepFunctie {
            get {
                return ResourceManager.GetString("FoutieveGroepFunctie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minstens {0} leden moeten de functie &apos;{1}&apos; hebben..
        /// </summary>
        internal static string FunctieLeeg {
            get {
                return ResourceManager.GetString("FunctieLeeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slechts {0} leden mogen de functie &apos;{1}&apos; hebben..
        /// </summary>
        internal static string FunctieVol {
            get {
                return ResourceManager.GetString("FunctieVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geboortedatum moet gekend zijn..
        /// </summary>
        internal static string GeboorteDatumOntbreekt {
            get {
                return ResourceManager.GetString("GeboorteDatumOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze afdeling is niet gekoppeld aan je groep(en)..
        /// </summary>
        internal static string GeenGavAfdeling {
            get {
                return ResourceManager.GetString("GeenGavAfdeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze categorie is niet gekoppeld aan je groep(en)..
        /// </summary>
        internal static string GeenGavCategorie {
            get {
                return ResourceManager.GetString("GeenGavCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De categorie en/of de persoon zijn niet gekoppeld aan je groep(en)..
        /// </summary>
        internal static string GeenGavCategoriePersoon {
            get {
                return ResourceManager.GetString("GeenGavCategoriePersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit is geen communicatievorm van een van jouw personen..
        /// </summary>
        internal static string GeenGavCommVorm {
            get {
                return ResourceManager.GetString("GeenGavCommVorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze functie is niet gekoppeld aan je groep(en)..
        /// </summary>
        internal static string GeenGavFunctie {
            get {
                return ResourceManager.GetString("GeenGavFunctie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze persoon is niet gekoppeld aan je groep(en)..
        /// </summary>
        internal static string GeenGavGelieerdePersoon {
            get {
                return ResourceManager.GetString("GeenGavGelieerdePersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent geen GAV van deze groep..
        /// </summary>
        internal static string GeenGavGroep {
            get {
                return ResourceManager.GetString("GeenGavGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit werkjaar is niet gekoppeld aan je groep(en)..
        /// </summary>
        internal static string GeenGavGroepsWerkJaar {
            get {
                return ResourceManager.GetString("GeenGavGroepsWerkJaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit lid is niet gekoppeld aan je groep(en)..
        /// </summary>
        internal static string GeenGavLid {
            get {
                return ResourceManager.GetString("GeenGavLid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er werd geen geschikte afdeling gevonden voor deze persoon..
        /// </summary>
        internal static string GeenGeschikteAfdeling {
            get {
                return ResourceManager.GetString("GeenGeschikteAfdeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze operatie is enkel beschikbaar voor super-GAV-goden..
        /// </summary>
        internal static string GeenSuperGav {
            get {
                return ResourceManager.GetString("GeenSuperGav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string InstapPeriode {
            get {
                return ResourceManager.GetString("InstapPeriode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De persoon is te jong..
        /// </summary>
        internal static string TeJong {
            get {
                return ResourceManager.GetString("TeJong", resourceCulture);
            }
        }
    }
}
