//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Gap.Workers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Gap.Workers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkel het nationaal secretariaat mag AD-nummers wijzigen..
        /// </summary>
        internal static string AdNummerNietWijzigen {
            get {
                return ResourceManager.GetString("AdNummerNietWijzigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minstens 1 gevraagde afdeling is niet beschikbaar in dit werkjaar..
        /// </summary>
        internal static string AfdelingNietBeschikbaar {
            get {
                return ResourceManager.GetString("AfdelingNietBeschikbaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een afdeling te activeren in een groepswerkjaar van een andere groep.  Prutser!.
        /// </summary>
        internal static string AfdelingNietVanGroep {
            get {
                return ResourceManager.GetString("AfdelingNietVanGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AfdelingsJaar kan niet verwijderd worden omdat er nog leden of leiding in deze afdeling zitten..
        /// </summary>
        internal static string AfdelingsJaarBevatLeden {
            get {
                return ResourceManager.GetString("AfdelingsJaarBevatLeden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een categorie met code &apos;{0}&apos;..
        /// </summary>
        internal static string CategorieBestaatAl {
            get {
                return ResourceManager.GetString("CategorieBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog personen gekoppeld aan deze categorie..
        /// </summary>
        internal static string CategorieNietLeeg {
            get {
                return ResourceManager.GetString("CategorieNietLeeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is geen geldige waarde voor {1}.
        /// </summary>
        internal static string CommunicatieVormValidatieFeedback {
            get {
                return ResourceManager.GetString("CommunicatieVormValidatieFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een groepswerkjaar in dat werkjaar.
        /// </summary>
        internal static string DubbelGroepswerkjaar {
            get {
                return ResourceManager.GetString("DubbelGroepswerkjaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog geen voorkeursadres ingegeven voor {0}; je kan er dus ook geen Dubbelpuntabonnement voor bestellen..
        /// </summary>
        internal static string DubbelPuntZonderAdres {
            get {
                return ResourceManager.GetString("DubbelPuntZonderAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begindatum mag niet later zijn dan einddatum.
        /// </summary>
        internal static string FouteDatumVolgorde {
            get {
                return ResourceManager.GetString("FouteDatumVolgorde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze persoon is niet gekoppeld aan de groep waarvan je hem/haar lid wil maken..
        /// </summary>
        internal static string FoutiefGroepsWerkJaar {
            get {
                return ResourceManager.GetString("FoutiefGroepsWerkJaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een lid te koppelen aan een functie die niet geldig is voor het gegeven werkjaar..
        /// </summary>
        internal static string FoutiefGroepsWerkJaarFunctie {
            get {
                return ResourceManager.GetString("FoutiefGroepsWerkJaarFunctie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze functie is niet toegelaten voor dit type lid (kind/leiding)..
        /// </summary>
        internal static string FoutiefLidType {
            get {
                return ResourceManager.GetString("FoutiefLidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kan geen lid van de ene groep koppelen aan een afdeling van een andere..
        /// </summary>
        internal static string FoutieveGroepAfdeling {
            get {
                return ResourceManager.GetString("FoutieveGroepAfdeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een persoon te koppelen aan een categorie uit een andere groep..
        /// </summary>
        internal static string FoutieveGroepCategorie {
            get {
                return ResourceManager.GetString("FoutieveGroepCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een lid te koppelen aan een categorie uit een andere groep..
        /// </summary>
        internal static string FoutieveGroepFunctie {
            get {
                return ResourceManager.GetString("FoutieveGroepFunctie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minstens {0} leden moeten de functie &apos;{1}&apos; hebben..
        /// </summary>
        internal static string FunctieLeeg {
            get {
                return ResourceManager.GetString("FunctieLeeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog leden of leid(st)ers die die functie hebben..
        /// </summary>
        internal static string FunctieNietLeeg {
            get {
                return ResourceManager.GetString("FunctieNietLeeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slechts {0} leden mogen de functie &apos;{1}&apos; hebben..
        /// </summary>
        internal static string FunctieVol {
            get {
                return ResourceManager.GetString("FunctieVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geboortedatum moet gekend zijn..
        /// </summary>
        internal static string GeboorteDatumOntbreekt {
            get {
                return ResourceManager.GetString("GeboorteDatumOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen afdeling in jullie groep voor die leeftijd. Je maakt er best eerst een aan (of controleer de leeftijd van wie je wilt inschrijven)..
        /// </summary>
        internal static string GeenAfdelingVoorLeeftijd {
            get {
                return ResourceManager.GetString("GeenAfdelingVoorLeeftijd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen toegang..
        /// </summary>
        internal static string GeenGav {
            get {
                return ResourceManager.GetString("GeenGav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen geschikte afdeling gevonden voor deze persoon..
        /// </summary>
        internal static string GeenGeschikteAfdeling {
            get {
                return ResourceManager.GetString("GeenGeschikteAfdeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige WoonPlaatsID..
        /// </summary>
        internal static string GemeenteNietGevonden {
            get {
                return ResourceManager.GetString("GemeenteNietGevonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeerde iemand in te schrijven van wie het geslacht niet bekend is..
        /// </summary>
        internal static string GeslachtVerplicht {
            get {
                return ResourceManager.GetString("GeslachtVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkeerde groep..
        /// </summary>
        internal static string GroepsWerkJaarNietVanGroep {
            get {
                return ResourceManager.GetString("GroepsWerkJaarNietVanGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kan geen aanpassingen meer doen aan vorige werkjaren..
        /// </summary>
        internal static string GroepsWerkJaarVoorbij {
            get {
                return ResourceManager.GetString("GroepsWerkJaarVoorbij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kan geen kinderen inschrijven als je groep geen afdelingen heeft in het huidige werkjaar!.
        /// </summary>
        internal static string InschrijvenZonderAfdelingen {
            get {
                return ResourceManager.GetString("InschrijvenZonderAfdelingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De einddatum is niet geldig voor dit type verzekering..
        /// </summary>
        internal static string OngeldigeEindDatumVerzekering {
            get {
                return ResourceManager.GetString("OngeldigeEindDatumVerzekering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige geboortejaren voor het afdelingsjaar.
        /// </summary>
        internal static string OngeldigeGeboortejarenVoorAfdeling {
            get {
                return ResourceManager.GetString("OngeldigeGeboortejarenVoorAfdeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig lidtype..
        /// </summary>
        internal static string OngeldigLidType {
            get {
                return ResourceManager.GetString("OngeldigLidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig postnummer..
        /// </summary>
        internal static string OngeldigPostNummer {
            get {
                return ResourceManager.GetString("OngeldigPostNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze persoon heeft al een dergelijke verzekering gedurende een overlappende periode..
        /// </summary>
        internal static string OverlappendeVerzekering {
            get {
                return ResourceManager.GetString("OverlappendeVerzekering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen komen niet overeen..
        /// </summary>
        internal static string PersonenKomenNietOvereen {
            get {
                return ResourceManager.GetString("PersonenKomenNietOvereen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De persoon die je lid wilt maken is reeds overleden..
        /// </summary>
        internal static string PersoonIsOverleden {
            get {
                return ResourceManager.GetString("PersoonIsOverleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straat {0} met postnummer {1} niet gevonden..
        /// </summary>
        internal static string StraatNietGevonden {
            get {
                return ResourceManager.GetString("StraatNietGevonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je gaf geen straatnaam mee..
        /// </summary>
        internal static string StraatOntbreekt {
            get {
                return ResourceManager.GetString("StraatOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze persoon is nog te jong om leiding te worden.  Check eventueel geboortedatum en/of Chiroleeftijd..
        /// </summary>
        internal static string TeJongVoorLeiding {
            get {
                return ResourceManager.GetString("TeJongVoorLeiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De begindatum van een verzekering kan niet in het verleden liggen..
        /// </summary>
        internal static string VerzekeringInVerleden {
            get {
                return ResourceManager.GetString("VerzekeringInVerleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een of meerdere personen wonen al op het aangeduide adres..
        /// </summary>
        internal static string WonenDaarAl {
            get {
                return ResourceManager.GetString("WonenDaarAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je gaf geen woonplaats mee..
        /// </summary>
        internal static string WoonPlaatsOntbreekt {
            get {
                return ResourceManager.GetString("WoonPlaatsOntbreekt", resourceCulture);
            }
        }
    }
}
