//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Chiro.Gap.Workers.Properties {
    
    
    [CompilerGenerated()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1990-09-01")]
        public DateTime WerkjaarStartNationaal {
            get {
                return ((DateTime)(this["WerkjaarStartNationaal"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1990-10-15")]
        public DateTime WerkjaarVerplichteOvergang {
            get {
                return ((DateTime)(this["WerkjaarVerplichteOvergang"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("21")]
        public int LengteProbeerPeriode {
            get {
                return ((int)(this["LengteProbeerPeriode"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int MaxLidLeefTijd {
            get {
                return ((int)(this["MaxLidLeefTijd"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2000-07-01")]
        public DateTime BeginOvergangsPeriode {
            get {
                return ((DateTime)(this["BeginOvergangsPeriode"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public int MinLeidingLeefTijd {
            get {
                return ((int)(this["MinLeidingLeefTijd"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2627")]
        public int UniqueViolation {
            get {
                return ((int)(this["UniqueViolation"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1990-05-01")]
        public DateTime BivakAangifteStart {
            get {
                return ((DateTime)(this["BivakAangifteStart"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2011")]
        public int MinWerkJaarLidOverzetten {
            get {
                return ((int)(this["MinWerkJaarLidOverzetten"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1990-11-01")]
        public DateTime EindeGebruikersRecht {
            get {
                return ((DateTime)(this["EindeGebruikersRecht"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("gaplive")]
        public string LiveConnSubstring {
            get {
                return ((string)(this["LiveConnSubstring"]));
            }
        }
    }
}
