//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("ChiroGroepModel", "FK_CommunicatieVorm_Persoon", "Persoon", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Cg2.Orm.Persoon), "CommunicatieVorm", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cg2.Orm.CommunicatieVorm))]

// Original file name:
// Generation date: 9/02/2009 14:34:31
namespace Cg2.Orm
{
    
    /// <summary>
    /// There are no comments for ChiroGroepEntities in the schema.
    /// </summary>
    public partial class ChiroGroepEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ChiroGroepEntities object using the connection string found in the 'ChiroGroepEntities' section of the application configuration file.
        /// </summary>
        public ChiroGroepEntities() : 
                base("name=ChiroGroepEntities", "ChiroGroepEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ChiroGroepEntities object.
        /// </summary>
        public ChiroGroepEntities(string connectionString) : 
                base(connectionString, "ChiroGroepEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ChiroGroepEntities object.
        /// </summary>
        public ChiroGroepEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ChiroGroepEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Groep in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Groep> Groep
        {
            get
            {
                if ((this._Groep == null))
                {
                    this._Groep = base.CreateQuery<Groep>("[Groep]");
                }
                return this._Groep;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Groep> _Groep;
        /// <summary>
        /// There are no comments for CommunicatieVorm in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CommunicatieVorm> CommunicatieVorm
        {
            get
            {
                if ((this._CommunicatieVorm == null))
                {
                    this._CommunicatieVorm = base.CreateQuery<CommunicatieVorm>("[CommunicatieVorm]");
                }
                return this._CommunicatieVorm;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CommunicatieVorm> _CommunicatieVorm;
        /// <summary>
        /// There are no comments for Persoon in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Persoon> Persoon
        {
            get
            {
                if ((this._Persoon == null))
                {
                    this._Persoon = base.CreateQuery<Persoon>("[Persoon]");
                }
                return this._Persoon;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Persoon> _Persoon;
        /// <summary>
        /// There are no comments for Groep in the schema.
        /// </summary>
        public void AddToGroep(Groep groep)
        {
            base.AddObject("Groep", groep);
        }
        /// <summary>
        /// There are no comments for CommunicatieVorm in the schema.
        /// </summary>
        public void AddToCommunicatieVorm(CommunicatieVorm communicatieVorm)
        {
            base.AddObject("CommunicatieVorm", communicatieVorm);
        }
        /// <summary>
        /// There are no comments for Persoon in the schema.
        /// </summary>
        public void AddToPersoon(Persoon persoon)
        {
            base.AddObject("Persoon", persoon);
        }
    }
    /// <summary>
    /// There are no comments for ChiroGroepModel.ChiroGroep in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ChiroGroepModel", Name="ChiroGroep")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ChiroGroep : Groep
    {
        /// <summary>
        /// Create a new ChiroGroep object.
        /// </summary>
        /// <param name="naam">Initial value of Naam.</param>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="versie">Initial value of Versie.</param>
        /// <param name="businessKey">Initial value of BusinessKey.</param>
        public static ChiroGroep CreateChiroGroep(string naam, int id, byte[] versie, global::System.Guid businessKey)
        {
            ChiroGroep chiroGroep = new ChiroGroep();
            chiroGroep.Naam = naam;
            chiroGroep.ID = id;
            chiroGroep.Versie = versie;
            chiroGroep.BusinessKey = businessKey;
            return chiroGroep;
        }
    }
    /// <summary>
    /// There are no comments for ChiroGroepModel.Groep in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ChiroGroepModel", Name="Groep")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    [global::System.Runtime.Serialization.KnownTypeAttribute(typeof(global::Cg2.Orm.ChiroGroep))]
    public partial class Groep : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Groep object.
        /// </summary>
        /// <param name="naam">Initial value of Naam.</param>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="versie">Initial value of Versie.</param>
        /// <param name="businessKey">Initial value of BusinessKey.</param>
        public static Groep CreateGroep(string naam, int id, byte[] versie, global::System.Guid businessKey)
        {
            Groep groep = new Groep();
            groep.Naam = naam;
            groep.ID = id;
            groep.Versie = versie;
            groep.BusinessKey = businessKey;
            return groep;
        }
        /// <summary>
        /// There are no comments for Property Naam in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam
        {
            get
            {
                return this._Naam;
            }
            set
            {
                this.OnNaamChanging(value);
                this.ReportPropertyChanging("Naam");
                this._Naam = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Naam");
                this.OnNaamChanged();
            }
        }
        private string _Naam;
        partial void OnNaamChanging(string value);
        partial void OnNaamChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property OprichtingsJaar in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> OprichtingsJaar
        {
            get
            {
                return this._OprichtingsJaar;
            }
            set
            {
                this.OnOprichtingsJaarChanging(value);
                this.ReportPropertyChanging("OprichtingsJaar");
                this._OprichtingsJaar = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OprichtingsJaar");
                this.OnOprichtingsJaarChanged();
            }
        }
        private global::System.Nullable<int> _OprichtingsJaar;
        partial void OnOprichtingsJaarChanging(global::System.Nullable<int> value);
        partial void OnOprichtingsJaarChanged();
        /// <summary>
        /// There are no comments for Property WebSite in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string WebSite
        {
            get
            {
                return this._WebSite;
            }
            set
            {
                this.OnWebSiteChanging(value);
                this.ReportPropertyChanging("WebSite");
                this._WebSite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("WebSite");
                this.OnWebSiteChanged();
            }
        }
        private string _WebSite;
        partial void OnWebSiteChanging(string value);
        partial void OnWebSiteChanged();
        /// <summary>
        /// There are no comments for Property Logo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Logo
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Logo);
            }
            set
            {
                this.OnLogoChanging(value);
                this.ReportPropertyChanging("Logo");
                this._Logo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Logo");
                this.OnLogoChanged();
            }
        }
        private byte[] _Logo;
        partial void OnLogoChanging(byte[] value);
        partial void OnLogoChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Versie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Versie
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Versie);
            }
            set
            {
                this.OnVersieChanging(value);
                this.ReportPropertyChanging("Versie");
                this._Versie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Versie");
                this.OnVersieChanged();
            }
        }
        private byte[] _Versie;
        partial void OnVersieChanging(byte[] value);
        partial void OnVersieChanged();
        /// <summary>
        /// There are no comments for Property BusinessKey in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid BusinessKey
        {
            get
            {
                return this._BusinessKey;
            }
            set
            {
                this.OnBusinessKeyChanging(value);
                this.ReportPropertyChanging("BusinessKey");
                this._BusinessKey = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BusinessKey");
                this.OnBusinessKeyChanged();
            }
        }
        private global::System.Guid _BusinessKey;
        partial void OnBusinessKeyChanging(global::System.Guid value);
        partial void OnBusinessKeyChanged();
    }
    /// <summary>
    /// There are no comments for ChiroGroepModel.CommunicatieVorm in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ChiroGroepModel", Name="CommunicatieVorm")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CommunicatieVorm : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CommunicatieVorm object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="isGezinsgebonden">Initial value of IsGezinsgebonden.</param>
        /// <param name="voorkeur">Initial value of Voorkeur.</param>
        /// <param name="versie">Initial value of Versie.</param>
        public static CommunicatieVorm CreateCommunicatieVorm(int id, bool isGezinsgebonden, bool voorkeur, byte[] versie)
        {
            CommunicatieVorm communicatieVorm = new CommunicatieVorm();
            communicatieVorm.ID = id;
            communicatieVorm.IsGezinsgebonden = isGezinsgebonden;
            communicatieVorm.Voorkeur = voorkeur;
            communicatieVorm.Versie = versie;
            return communicatieVorm;
        }
        /// <summary>
        /// There are no comments for Property Nota in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota
        {
            get
            {
                return this._Nota;
            }
            set
            {
                this.OnNotaChanging(value);
                this.ReportPropertyChanging("Nota");
                this._Nota = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nota");
                this.OnNotaChanged();
            }
        }
        private string _Nota;
        partial void OnNotaChanging(string value);
        partial void OnNotaChanged();
        /// <summary>
        /// There are no comments for Property Nummer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Nummer
        {
            get
            {
                return this._Nummer;
            }
            set
            {
                this.OnNummerChanging(value);
                this.ReportPropertyChanging("Nummer");
                this._Nummer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nummer");
                this.OnNummerChanged();
            }
        }
        private string _Nummer;
        partial void OnNummerChanging(string value);
        partial void OnNummerChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property CommunicatieTypeInt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CommunicatieTypeInt
        {
            get
            {
                return this._CommunicatieTypeInt;
            }
            set
            {
                this.OnCommunicatieTypeIntChanging(value);
                this.ReportPropertyChanging("CommunicatieTypeInt");
                this._CommunicatieTypeInt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CommunicatieTypeInt");
                this.OnCommunicatieTypeIntChanged();
            }
        }
        private global::System.Nullable<int> _CommunicatieTypeInt;
        partial void OnCommunicatieTypeIntChanging(global::System.Nullable<int> value);
        partial void OnCommunicatieTypeIntChanged();
        /// <summary>
        /// There are no comments for Property IsGezinsgebonden in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGezinsgebonden
        {
            get
            {
                return this._IsGezinsgebonden;
            }
            set
            {
                this.OnIsGezinsgebondenChanging(value);
                this.ReportPropertyChanging("IsGezinsgebonden");
                this._IsGezinsgebonden = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsGezinsgebonden");
                this.OnIsGezinsgebondenChanged();
            }
        }
        private bool _IsGezinsgebonden;
        partial void OnIsGezinsgebondenChanging(bool value);
        partial void OnIsGezinsgebondenChanged();
        /// <summary>
        /// There are no comments for Property Voorkeur in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool Voorkeur
        {
            get
            {
                return this._Voorkeur;
            }
            set
            {
                this.OnVoorkeurChanging(value);
                this.ReportPropertyChanging("Voorkeur");
                this._Voorkeur = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Voorkeur");
                this.OnVoorkeurChanged();
            }
        }
        private bool _Voorkeur;
        partial void OnVoorkeurChanging(bool value);
        partial void OnVoorkeurChanged();
        /// <summary>
        /// There are no comments for Property Versie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Versie
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Versie);
            }
            set
            {
                this.OnVersieChanging(value);
                this.ReportPropertyChanging("Versie");
                this._Versie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Versie");
                this.OnVersieChanged();
            }
        }
        private byte[] _Versie;
        partial void OnVersieChanging(byte[] value);
        partial void OnVersieChanged();
        /// <summary>
        /// There are no comments for Persoon in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ChiroGroepModel", "FK_CommunicatieVorm_Persoon", "Persoon")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Persoon Persoon
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Persoon>("ChiroGroepModel.FK_CommunicatieVorm_Persoon", "Persoon").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Persoon>("ChiroGroepModel.FK_CommunicatieVorm_Persoon", "Persoon").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Persoon in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Persoon> PersoonReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Persoon>("ChiroGroepModel.FK_CommunicatieVorm_Persoon", "Persoon");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Persoon>("ChiroGroepModel.FK_CommunicatieVorm_Persoon", "Persoon", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for ChiroGroepModel.Persoon in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ChiroGroepModel", Name="Persoon")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Persoon : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Persoon object.
        /// </summary>
        /// <param name="naam">Initial value of Naam.</param>
        /// <param name="geslachtsInt">Initial value of GeslachtsInt.</param>
        /// <param name="chiroLeefTijd">Initial value of ChiroLeefTijd.</param>
        /// <param name="businessKey">Initial value of BusinessKey.</param>
        /// <param name="id">Initial value of ID.</param>
        public static Persoon CreatePersoon(string naam, int geslachtsInt, int chiroLeefTijd, global::System.Guid businessKey, int id)
        {
            Persoon persoon = new Persoon();
            persoon.Naam = naam;
            persoon.GeslachtsInt = geslachtsInt;
            persoon.ChiroLeefTijd = chiroLeefTijd;
            persoon.BusinessKey = businessKey;
            persoon.ID = id;
            return persoon;
        }
        /// <summary>
        /// There are no comments for Property AdNummer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> AdNummer
        {
            get
            {
                return this._AdNummer;
            }
            set
            {
                this.OnAdNummerChanging(value);
                this.ReportPropertyChanging("AdNummer");
                this._AdNummer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AdNummer");
                this.OnAdNummerChanged();
            }
        }
        private global::System.Nullable<int> _AdNummer;
        partial void OnAdNummerChanging(global::System.Nullable<int> value);
        partial void OnAdNummerChanged();
        /// <summary>
        /// There are no comments for Property Naam in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam
        {
            get
            {
                return this._Naam;
            }
            set
            {
                this.OnNaamChanging(value);
                this.ReportPropertyChanging("Naam");
                this._Naam = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Naam");
                this.OnNaamChanged();
            }
        }
        private string _Naam;
        partial void OnNaamChanging(string value);
        partial void OnNaamChanged();
        /// <summary>
        /// There are no comments for Property VoorNaam in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VoorNaam
        {
            get
            {
                return this._VoorNaam;
            }
            set
            {
                this.OnVoorNaamChanging(value);
                this.ReportPropertyChanging("VoorNaam");
                this._VoorNaam = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("VoorNaam");
                this.OnVoorNaamChanged();
            }
        }
        private string _VoorNaam;
        partial void OnVoorNaamChanging(string value);
        partial void OnVoorNaamChanged();
        /// <summary>
        /// There are no comments for Property GeboorteDatum in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> GeboorteDatum
        {
            get
            {
                return this._GeboorteDatum;
            }
            set
            {
                this.OnGeboorteDatumChanging(value);
                this.ReportPropertyChanging("GeboorteDatum");
                this._GeboorteDatum = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GeboorteDatum");
                this.OnGeboorteDatumChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _GeboorteDatum;
        partial void OnGeboorteDatumChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnGeboorteDatumChanged();
        /// <summary>
        /// There are no comments for Property GeslachtsInt in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int GeslachtsInt
        {
            get
            {
                return this._GeslachtsInt;
            }
            set
            {
                this.OnGeslachtsIntChanging(value);
                this.ReportPropertyChanging("GeslachtsInt");
                this._GeslachtsInt = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GeslachtsInt");
                this.OnGeslachtsIntChanged();
            }
        }
        private int _GeslachtsInt;
        partial void OnGeslachtsIntChanging(int value);
        partial void OnGeslachtsIntChanged();
        /// <summary>
        /// There are no comments for Property ChiroLeefTijd in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ChiroLeefTijd
        {
            get
            {
                return this._ChiroLeefTijd;
            }
            set
            {
                this.OnChiroLeefTijdChanging(value);
                this.ReportPropertyChanging("ChiroLeefTijd");
                this._ChiroLeefTijd = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChiroLeefTijd");
                this.OnChiroLeefTijdChanged();
            }
        }
        private int _ChiroLeefTijd;
        partial void OnChiroLeefTijdChanging(int value);
        partial void OnChiroLeefTijdChanged();
        /// <summary>
        /// There are no comments for Property SterfDatum in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> SterfDatum
        {
            get
            {
                return this._SterfDatum;
            }
            set
            {
                this.OnSterfDatumChanging(value);
                this.ReportPropertyChanging("SterfDatum");
                this._SterfDatum = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SterfDatum");
                this.OnSterfDatumChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _SterfDatum;
        partial void OnSterfDatumChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnSterfDatumChanged();
        /// <summary>
        /// There are no comments for Property BusinessKey in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid BusinessKey
        {
            get
            {
                return this._BusinessKey;
            }
            set
            {
                this.OnBusinessKeyChanging(value);
                this.ReportPropertyChanging("BusinessKey");
                this._BusinessKey = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BusinessKey");
                this.OnBusinessKeyChanged();
            }
        }
        private global::System.Guid _BusinessKey;
        partial void OnBusinessKeyChanging(global::System.Guid value);
        partial void OnBusinessKeyChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Versie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Versie
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Versie);
            }
            set
            {
                this.OnVersieChanging(value);
                this.ReportPropertyChanging("Versie");
                this._Versie = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Versie");
                this.OnVersieChanged();
            }
        }
        private byte[] _Versie;
        partial void OnVersieChanging(byte[] value);
        partial void OnVersieChanged();
        /// <summary>
        /// There are no comments for Communicatie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("ChiroGroepModel", "FK_CommunicatieVorm_Persoon", "CommunicatieVorm")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CommunicatieVorm> Communicatie
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CommunicatieVorm>("ChiroGroepModel.FK_CommunicatieVorm_Persoon", "CommunicatieVorm");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CommunicatieVorm>("ChiroGroepModel.FK_CommunicatieVorm_Persoon", "CommunicatieVorm", value);
                }
            }
        }
    }
}
