//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CgWeb.PersonenServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonenServiceReference.IPersonenService")]
    public interface IPersonenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/Hallo", ReplyAction="http://tempuri.org/IPersonenService/HalloResponse")]
        string Hallo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/PersoonGet", ReplyAction="http://tempuri.org/IPersonenService/PersoonGetResponse")]
        CgDal.Persoon PersoonGet(int persoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/PersoonMetDetailsGet", ReplyAction="http://tempuri.org/IPersonenService/PersoonMetDetailsGetResponse")]
        CgDal.Persoon PersoonMetDetailsGet(int PersoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/GelieerdePersonenInfoGet", ReplyAction="http://tempuri.org/IPersonenService/GelieerdePersonenInfoGetResponse")]
        CgDal.vPersoonsInfo[] GelieerdePersonenInfoGet(int GroepID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonenService/PersoonUpdaten", ReplyAction="http://tempuri.org/IPersonenService/PersoonUpdatenResponse")]
        int PersoonUpdaten(CgDal.Persoon persoon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPersonenServiceChannel : CgWeb.PersonenServiceReference.IPersonenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PersonenServiceClient : System.ServiceModel.ClientBase<CgWeb.PersonenServiceReference.IPersonenService>, CgWeb.PersonenServiceReference.IPersonenService {
        
        public PersonenServiceClient() {
        }
        
        public PersonenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hallo() {
            return base.Channel.Hallo();
        }
        
        public CgDal.Persoon PersoonGet(int persoonID) {
            return base.Channel.PersoonGet(persoonID);
        }
        
        public CgDal.Persoon PersoonMetDetailsGet(int PersoonID) {
            return base.Channel.PersoonMetDetailsGet(PersoonID);
        }
        
        public CgDal.vPersoonsInfo[] GelieerdePersonenInfoGet(int GroepID) {
            return base.Channel.GelieerdePersonenInfoGet(GroepID);
        }
        
        public int PersoonUpdaten(CgDal.Persoon persoon) {
            return base.Channel.PersoonUpdaten(persoon);
        }
    }
}
