//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApp2.GelieerdePersonenServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CgFaultException", Namespace="http://schemas.datacontract.org/2004/07/Cg2.ServiceContracts.FaultContracts")]
    [System.SerializableAttribute()]
    public partial class CgFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoodschapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcWebApp2.GelieerdePersonenServiceReference.FoutCode CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boodschap {
            get {
                return this.BoodschapField;
            }
            set {
                if ((object.ReferenceEquals(this.BoodschapField, value) != true)) {
                    this.BoodschapField = value;
                    this.RaisePropertyChanged("Boodschap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcWebApp2.GelieerdePersonenServiceReference.FoutCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoutCode", Namespace="http://schemas.datacontract.org/2004/07/Cg2.ServiceContracts.FaultContracts")]
    public enum FoutCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnbekendeStraat = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnbekendeGemeente = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GelieerdePersonenServiceReference.IGelieerdePersonenService")]
    public interface IGelieerdePersonenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/PaginaOphalen", ReplyAction="http://tempuri.org/IGelieerdePersonenService/PaginaOphalenResponse")]
        System.Collections.Generic.List<Cg2.Orm.GelieerdePersoon> PaginaOphalen(out int aantalOpgehaald, int groepID, int pagina, int paginaGrootte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/PaginaOphalenMetLidInfo", ReplyAction="http://tempuri.org/IGelieerdePersonenService/PaginaOphalenMetLidInfoResponse")]
        System.Collections.Generic.List<Cg2.Orm.GelieerdePersoon> PaginaOphalenMetLidInfo(out int aantalOpgehaald, int groepID, int pagina, int paginaGrootte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/PersoonOphalenMetDetails", ReplyAction="http://tempuri.org/IGelieerdePersonenService/PersoonOphalenMetDetailsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cg2.Orm.ChiroGroep))]
        Cg2.Orm.GelieerdePersoon PersoonOphalenMetDetails(int gelieerdePersoonID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/PersoonOphalenMetCustomDetails", ReplyAction="http://tempuri.org/IGelieerdePersonenService/PersoonOphalenMetCustomDetailsRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cg2.Orm.ChiroGroep))]
        Cg2.Orm.GelieerdePersoon PersoonOphalenMetCustomDetails(int gelieerdePersoonID, Cg2.Orm.PersoonsInfo gevraagd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/PersoonBewaren", ReplyAction="http://tempuri.org/IGelieerdePersonenService/PersoonBewarenResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Cg2.Orm.ChiroGroep))]
        void PersoonBewaren(Cg2.Orm.GelieerdePersoon persoon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/AdresMetBewonersOphalen", ReplyAction="http://tempuri.org/IGelieerdePersonenService/AdresMetBewonersOphalenResponse")]
        Cg2.Orm.Adres AdresMetBewonersOphalen(int adresID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGelieerdePersonenService/Verhuizen", ReplyAction="http://tempuri.org/IGelieerdePersonenService/VerhuizenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MvcWebApp2.GelieerdePersonenServiceReference.CgFaultException), Action="http://tempuri.org/IGelieerdePersonenService/VerhuizenCgFaultExceptionFault", Name="CgFaultException", Namespace="http://schemas.datacontract.org/2004/07/Cg2.ServiceContracts.FaultContracts")]
        void Verhuizen(System.Collections.Generic.List<int> gelieerdePersonen, Cg2.Orm.Adres nieuwAdres, int oudAdresID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IGelieerdePersonenServiceChannel : MvcWebApp2.GelieerdePersonenServiceReference.IGelieerdePersonenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GelieerdePersonenServiceClient : System.ServiceModel.ClientBase<MvcWebApp2.GelieerdePersonenServiceReference.IGelieerdePersonenService>, MvcWebApp2.GelieerdePersonenServiceReference.IGelieerdePersonenService {
        
        public GelieerdePersonenServiceClient() {
        }
        
        public GelieerdePersonenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GelieerdePersonenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GelieerdePersonenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GelieerdePersonenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Cg2.Orm.GelieerdePersoon> PaginaOphalen(out int aantalOpgehaald, int groepID, int pagina, int paginaGrootte) {
            return base.Channel.PaginaOphalen(out aantalOpgehaald, groepID, pagina, paginaGrootte);
        }
        
        public System.Collections.Generic.List<Cg2.Orm.GelieerdePersoon> PaginaOphalenMetLidInfo(out int aantalOpgehaald, int groepID, int pagina, int paginaGrootte) {
            return base.Channel.PaginaOphalenMetLidInfo(out aantalOpgehaald, groepID, pagina, paginaGrootte);
        }
        
        public Cg2.Orm.GelieerdePersoon PersoonOphalenMetDetails(int gelieerdePersoonID) {
            return base.Channel.PersoonOphalenMetDetails(gelieerdePersoonID);
        }
        
        public Cg2.Orm.GelieerdePersoon PersoonOphalenMetCustomDetails(int gelieerdePersoonID, Cg2.Orm.PersoonsInfo gevraagd) {
            return base.Channel.PersoonOphalenMetCustomDetails(gelieerdePersoonID, gevraagd);
        }
        
        public void PersoonBewaren(Cg2.Orm.GelieerdePersoon persoon) {
            base.Channel.PersoonBewaren(persoon);
        }
        
        public Cg2.Orm.Adres AdresMetBewonersOphalen(int adresID) {
            return base.Channel.AdresMetBewonersOphalen(adresID);
        }
        
        public void Verhuizen(System.Collections.Generic.List<int> gelieerdePersonen, Cg2.Orm.Adres nieuwAdres, int oudAdresID) {
            base.Channel.Verhuizen(gelieerdePersonen, nieuwAdres, oudAdresID);
        }
    }
}
