//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Kip.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Kip.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen bewoner op adres {0} {1} {2}, {3} {4}.
        /// </summary>
        internal static string AdresZonderPersoon {
            get {
                return ResourceManager.GetString("AdresZonderPersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to België.
        /// </summary>
        internal static string Belgie {
            get {
                return ResourceManager.GetString("Belgie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan communicatie {2} van onbekend persoon {0} {1} niet bewaren..
        /// </summary>
        internal static string CommunicatieOnbekendePersoon {
            get {
                return ResourceManager.GetString("CommunicatieOnbekendePersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan communicatie {2} van onbekende persoon {0} {1} niet verwijderen..
        /// </summary>
        internal static string CommVerwijderenOnbekendePersoon {
            get {
                return ResourceManager.GetString("CommVerwijderenOnbekendePersoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid {0} {1} niet gevonden voor werkjaar {3}, groep {2}.
        /// </summary>
        internal static string LidNietGevonden {
            get {
                return ResourceManager.GetString("LidNietGevonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van persoon onvolledig: {0} {1} ({2}).
        /// </summary>
        internal static string NegeerPersoonOnvolledigeNaam {
            get {
                return ResourceManager.GetString("NegeerPersoonOnvolledigeNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres van persoon zonder AD-nummer niet bewaard. {0} {1}.
        /// </summary>
        internal static string NegeerPersoonZonderAD {
            get {
                return ResourceManager.GetString("NegeerPersoonZonderAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoon niet gevonden: {0} {1}.
        /// </summary>
        internal static string PersoonNietGevonden {
            get {
                return ResourceManager.GetString("PersoonNietGevonden", resourceCulture);
            }
        }
    }
}
