INSERT INTO lid.OfficieleAfdeling (Naam)
VALUES     ('Ribbels')
INSERT INTO lid.OfficieleAfdeling (Naam)
VALUES     ('Speelclub')
INSERT INTO lid.OfficieleAfdeling (Naam)
VALUES     ('Rakwi''s')
INSERT INTO lid.OfficieleAfdeling (Naam)
VALUES     ('Tito''s')
INSERT INTO lid.OfficieleAfdeling (Naam)
VALUES     ('Keti''s')
INSERT INTO lid.OfficieleAfdeling (Naam)
VALUES     ('Aspiranten')