//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Ad.LoginService.MailServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intranet/MailService", ConfigurationName="MailServiceReference.MailServiceSoap")]
    public interface MailServiceSoap {
        
        // CODEGEN: Generating message contract since element name prmVanNaam from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurMail", ReplyAction="*")]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurMailResponse VerstuurMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurMailRequest request);
        
        // CODEGEN: Generating message contract since element name prmVoorAdres from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurSomMail", ReplyAction="*")]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailResponse VerstuurSomMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailRequest request);
        
        // CODEGEN: Generating message contract since element name prmOver from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurLogMail", ReplyAction="*")]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailResponse VerstuurLogMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailRequest request);
        
        // CODEGEN: Generating message contract since element name prmSoortMelding from namespace http://intranet/MailService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://intranet/MailService/VerstuurCustomLogMail", ReplyAction="*")]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailResponse VerstuurCustomLogMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurMailRequestBody Body;
        
        public VerstuurMailRequest() {
        }
        
        public VerstuurMailRequest(Chiro.Ad.LoginService.MailServiceReference.VerstuurMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmVanNaam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmVoorAdres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmOver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prmBoodschap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string prmApplicatieNaam;
        
        public VerstuurMailRequestBody() {
        }
        
        public VerstuurMailRequestBody(string prmVanNaam, string prmVoorAdres, string prmOver, string prmBoodschap, string prmApplicatieNaam) {
            this.prmVanNaam = prmVanNaam;
            this.prmVoorAdres = prmVoorAdres;
            this.prmOver = prmOver;
            this.prmBoodschap = prmBoodschap;
            this.prmApplicatieNaam = prmApplicatieNaam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurMailResponseBody Body;
        
        public VerstuurMailResponse() {
        }
        
        public VerstuurMailResponse(Chiro.Ad.LoginService.MailServiceReference.VerstuurMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurMailResult;
        
        public VerstuurMailResponseBody() {
        }
        
        public VerstuurMailResponseBody(Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurMailResult) {
            this.VerstuurMailResult = VerstuurMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurSomMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurSomMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailRequestBody Body;
        
        public VerstuurSomMailRequest() {
        }
        
        public VerstuurSomMailRequest(Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurSomMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmVoorAdres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmOver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmBoodschap;
        
        public VerstuurSomMailRequestBody() {
        }
        
        public VerstuurSomMailRequestBody(string prmVoorAdres, string prmOver, string prmBoodschap) {
            this.prmVoorAdres = prmVoorAdres;
            this.prmOver = prmOver;
            this.prmBoodschap = prmBoodschap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurSomMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurSomMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailResponseBody Body;
        
        public VerstuurSomMailResponse() {
        }
        
        public VerstuurSomMailResponse(Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurSomMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurSomMailResult;
        
        public VerstuurSomMailResponseBody() {
        }
        
        public VerstuurSomMailResponseBody(Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurSomMailResult) {
            this.VerstuurSomMailResult = VerstuurSomMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurLogMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurLogMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailRequestBody Body;
        
        public VerstuurLogMailRequest() {
        }
        
        public VerstuurLogMailRequest(Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurLogMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmOver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmBoodschap;
        
        public VerstuurLogMailRequestBody() {
        }
        
        public VerstuurLogMailRequestBody(string prmOver, string prmBoodschap) {
            this.prmOver = prmOver;
            this.prmBoodschap = prmBoodschap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurLogMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurLogMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailResponseBody Body;
        
        public VerstuurLogMailResponse() {
        }
        
        public VerstuurLogMailResponse(Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurLogMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurLogMailResult;
        
        public VerstuurLogMailResponseBody() {
        }
        
        public VerstuurLogMailResponseBody(Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurLogMailResult) {
            this.VerstuurLogMailResult = VerstuurLogMailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurCustomLogMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurCustomLogMail", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailRequestBody Body;
        
        public VerstuurCustomLogMailRequest() {
        }
        
        public VerstuurCustomLogMailRequest(Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurCustomLogMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmSoortMelding;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string prmOver;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prmBoodschap;
        
        public VerstuurCustomLogMailRequestBody() {
        }
        
        public VerstuurCustomLogMailRequestBody(string prmSoortMelding, string prmOver, string prmBoodschap) {
            this.prmSoortMelding = prmSoortMelding;
            this.prmOver = prmOver;
            this.prmBoodschap = prmBoodschap;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerstuurCustomLogMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerstuurCustomLogMailResponse", Namespace="http://intranet/MailService", Order=0)]
        public Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailResponseBody Body;
        
        public VerstuurCustomLogMailResponse() {
        }
        
        public VerstuurCustomLogMailResponse(Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://intranet/MailService")]
    public partial class VerstuurCustomLogMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurCustomLogMailResult;
        
        public VerstuurCustomLogMailResponseBody() {
        }
        
        public VerstuurCustomLogMailResponseBody(Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurCustomLogMailResult) {
            this.VerstuurCustomLogMailResult = VerstuurCustomLogMailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailServiceSoapChannel : Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServiceSoapClient : System.ServiceModel.ClientBase<Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap>, Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap {
        
        public MailServiceSoapClient() {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurMailResponse Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap.VerstuurMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurMailRequest request) {
            return base.Channel.VerstuurMail(request);
        }
        
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurMail(string prmVanNaam, string prmVoorAdres, string prmOver, string prmBoodschap, string prmApplicatieNaam) {
            Chiro.Ad.LoginService.MailServiceReference.VerstuurMailRequest inValue = new Chiro.Ad.LoginService.MailServiceReference.VerstuurMailRequest();
            inValue.Body = new Chiro.Ad.LoginService.MailServiceReference.VerstuurMailRequestBody();
            inValue.Body.prmVanNaam = prmVanNaam;
            inValue.Body.prmVoorAdres = prmVoorAdres;
            inValue.Body.prmOver = prmOver;
            inValue.Body.prmBoodschap = prmBoodschap;
            inValue.Body.prmApplicatieNaam = prmApplicatieNaam;
            Chiro.Ad.LoginService.MailServiceReference.VerstuurMailResponse retVal = ((Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap)(this)).VerstuurMail(inValue);
            return retVal.Body.VerstuurMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailResponse Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap.VerstuurSomMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailRequest request) {
            return base.Channel.VerstuurSomMail(request);
        }
        
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurSomMail(string prmVoorAdres, string prmOver, string prmBoodschap) {
            Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailRequest inValue = new Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailRequest();
            inValue.Body = new Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailRequestBody();
            inValue.Body.prmVoorAdres = prmVoorAdres;
            inValue.Body.prmOver = prmOver;
            inValue.Body.prmBoodschap = prmBoodschap;
            Chiro.Ad.LoginService.MailServiceReference.VerstuurSomMailResponse retVal = ((Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap)(this)).VerstuurSomMail(inValue);
            return retVal.Body.VerstuurSomMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailResponse Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap.VerstuurLogMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailRequest request) {
            return base.Channel.VerstuurLogMail(request);
        }
        
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurLogMail(string prmOver, string prmBoodschap) {
            Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailRequest inValue = new Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailRequest();
            inValue.Body = new Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailRequestBody();
            inValue.Body.prmOver = prmOver;
            inValue.Body.prmBoodschap = prmBoodschap;
            Chiro.Ad.LoginService.MailServiceReference.VerstuurLogMailResponse retVal = ((Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap)(this)).VerstuurLogMail(inValue);
            return retVal.Body.VerstuurLogMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailResponse Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap.VerstuurCustomLogMail(Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailRequest request) {
            return base.Channel.VerstuurCustomLogMail(request);
        }
        
        public Chiro.Ad.Domain.MailServiceReference.BerichtStatus VerstuurCustomLogMail(string prmSoortMelding, string prmOver, string prmBoodschap) {
            Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailRequest inValue = new Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailRequest();
            inValue.Body = new Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailRequestBody();
            inValue.Body.prmSoortMelding = prmSoortMelding;
            inValue.Body.prmOver = prmOver;
            inValue.Body.prmBoodschap = prmBoodschap;
            Chiro.Ad.LoginService.MailServiceReference.VerstuurCustomLogMailResponse retVal = ((Chiro.Ad.LoginService.MailServiceReference.MailServiceSoap)(this)).VerstuurCustomLogMail(inValue);
            return retVal.Body.VerstuurCustomLogMailResult;
        }
    }
}
