//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Chiro.Gap.Diagnostics.Orm
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class diagnosticEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new diagnosticEntities object using the connection string found in the 'diagnosticEntities' section of the application configuration file.
        /// </summary>
        public diagnosticEntities() : base("name=diagnosticEntities", "diagnosticEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new diagnosticEntities object.
        /// </summary>
        public diagnosticEntities(string connectionString) : base(connectionString, "diagnosticEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new diagnosticEntities object.
        /// </summary>
        public diagnosticEntities(EntityConnection connection) : base(connection, "diagnosticEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VerlorenAdres> vVerlorenAdressen
        {
            get
            {
                if ((_vVerlorenAdressen == null))
                {
                    _vVerlorenAdressen = base.CreateObjectSet<VerlorenAdres>("vVerlorenAdressen");
                }
                return _vVerlorenAdressen;
            }
        }
        private ObjectSet<VerlorenAdres> _vVerlorenAdressen;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vVerlorenAdressen EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovVerlorenAdressen(VerlorenAdres verlorenAdres)
        {
            base.AddObject("vVerlorenAdressen", verlorenAdres);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="diagnosticModel", Name="VerlorenAdres")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VerlorenAdres : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VerlorenAdres object.
        /// </summary>
        /// <param name="adNr">Initial value of the AdNr property.</param>
        /// <param name="gelieerdePersoonID">Initial value of the GelieerdePersoonID property.</param>
        public static VerlorenAdres CreateVerlorenAdres(global::System.Int32 adNr, global::System.Int32 gelieerdePersoonID)
        {
            VerlorenAdres verlorenAdres = new VerlorenAdres();
            verlorenAdres.AdNr = adNr;
            verlorenAdres.GelieerdePersoonID = gelieerdePersoonID;
            return verlorenAdres;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdNr
        {
            get
            {
                return _AdNr;
            }
            set
            {
                if (_AdNr != value)
                {
                    OnAdNrChanging(value);
                    ReportPropertyChanging("AdNr");
                    _AdNr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdNr");
                    OnAdNrChanged();
                }
            }
        }
        private global::System.Int32 _AdNr;
        partial void OnAdNrChanging(global::System.Int32 value);
        partial void OnAdNrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StamNr
        {
            get
            {
                return _StamNr;
            }
            set
            {
                OnStamNrChanging(value);
                ReportPropertyChanging("StamNr");
                _StamNr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StamNr");
                OnStamNrChanged();
            }
        }
        private global::System.String _StamNr;
        partial void OnStamNrChanging(global::System.String value);
        partial void OnStamNrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VoorNaam
        {
            get
            {
                return _VoorNaam;
            }
            set
            {
                OnVoorNaamChanging(value);
                ReportPropertyChanging("VoorNaam");
                _VoorNaam = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VoorNaam");
                OnVoorNaamChanged();
            }
        }
        private global::System.String _VoorNaam;
        partial void OnVoorNaamChanging(global::System.String value);
        partial void OnVoorNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GelieerdePersoonID
        {
            get
            {
                return _GelieerdePersoonID;
            }
            set
            {
                if (_GelieerdePersoonID != value)
                {
                    OnGelieerdePersoonIDChanging(value);
                    ReportPropertyChanging("GelieerdePersoonID");
                    _GelieerdePersoonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GelieerdePersoonID");
                    OnGelieerdePersoonIDChanged();
                }
            }
        }
        private global::System.Int32 _GelieerdePersoonID;
        partial void OnGelieerdePersoonIDChanging(global::System.Int32 value);
        partial void OnGelieerdePersoonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VoorkeursAdresID
        {
            get
            {
                return _VoorkeursAdresID;
            }
            set
            {
                OnVoorkeursAdresIDChanging(value);
                ReportPropertyChanging("VoorkeursAdresID");
                _VoorkeursAdresID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VoorkeursAdresID");
                OnVoorkeursAdresIDChanged();
            }
        }
        private Nullable<global::System.Int32> _VoorkeursAdresID;
        partial void OnVoorkeursAdresIDChanging(Nullable<global::System.Int32> value);
        partial void OnVoorkeursAdresIDChanged();

        #endregion
    
    }

    #endregion
    
}
