//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Gap.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Gap.WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De opgegeven waarde voldoet niet aan de voorwaarden..
        /// </summary>
        public static string AlgemeneValidatieFout {
            get {
                return ResourceManager.GetString("AlgemeneValidatieFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een categorie met code &apos;{0}&apos;..
        /// </summary>
        public static string CategorieCodeBestaatAl {
            get {
                return ResourceManager.GetString("CategorieCodeBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een categorie met &apos;{0}&apos; als beschrijving..
        /// </summary>
        public static string CategorieNaamBestaatAl {
            get {
                return ResourceManager.GetString("CategorieNaamBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog geen categorieën, dus kun je er ook geen mensen in stoppen. Maak categorieën aan op het tabblad &apos;Groep&apos;..
        /// </summary>
        public static string CategoriserenZonderCategorieënFout {
            get {
                return ResourceManager.GetString("CategoriserenZonderCategorieënFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De waarde voor {0} voldoet niet aan de verplichte structuur: {1}.
        /// </summary>
        public static string FormatValidatieFout {
            get {
                return ResourceManager.GetString("FormatValidatieFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen afdelingen geactiveerd voor dit werkjaar.  Pas eerst je &lt;a href=&apos;{0}&apos;&gt;afdelingsverdeling&lt;/a&gt; aan..
        /// </summary>
        public static string GeenActieveAfdelingen {
            get {
                return ResourceManager.GetString("GeenActieveAfdelingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groepsinstellingen.
        /// </summary>
        public static string GroepsInstellingenTitel {
            get {
                return ResourceManager.GetString("GroepsInstellingenTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lidgegevens.
        /// </summary>
        public static string LidGegevens {
            get {
                return ResourceManager.GetString("LidGegevens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die persoon is nu ingeschreven als lid van je groep..
        /// </summary>
        public static string LidGemaaktFeedback {
            get {
                return ResourceManager.GetString("LidGemaaktFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets foutgelopen, die persoon is nog niet ingeschreven als lid van je groep..
        /// </summary>
        public static string LidMakenMisluktFout {
            get {
                return ResourceManager.GetString("LidMakenMisluktFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog niemand geselecteerd, dus kun je die actie niet uitvoeren.
        /// </summary>
        public static string NiemandGeselecteerdFout {
            get {
                return ResourceManager.GetString("NiemandGeselecteerdFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe persoon.
        /// </summary>
        public static string NieuwePersoonTitel {
            get {
                return ResourceManager.GetString("NieuwePersoonTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overzicht.
        /// </summary>
        public static string Overzicht {
            get {
                return ResourceManager.GetString("Overzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De wijzigingen zijn opgeslagen.
        /// </summary>
        public static string WijzigingenOpgeslagenFeedback {
            get {
                return ResourceManager.GetString("WijzigingenOpgeslagenFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze persoon woont al op het gevraagde adres..
        /// </summary>
        public static string WoontDaarAl {
            get {
                return ResourceManager.GetString("WoontDaarAl", resourceCulture);
            }
        }
    }
}
