//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Gap.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Gap.WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres van de lokalen.
        /// </summary>
        public static string AdresLokalen {
            get {
                return ResourceManager.GetString("AdresLokalen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet het adres nog invullen van je bivak &lt;a href=&apos;{1}&apos;&gt; {0} &lt;/a&gt;..
        /// </summary>
        public static string AdresNogInvullenOpBivakAangifte {
            get {
                return ResourceManager.GetString("AdresNogInvullenOpBivakAangifte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gevraagde afdeling bestond niet in het werkjaar {0}-{1}..
        /// </summary>
        public static string AfdelingBestondNiet {
            get {
                return ResourceManager.GetString("AfdelingBestondNiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afdeling(en) bewerken.
        /// </summary>
        public static string AfdelingenAanpassen {
            get {
                return ResourceManager.GetString("AfdelingenAanpassen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afdeling is verplicht..
        /// </summary>
        public static string AfdelingKindVerplicht {
            get {
                return ResourceManager.GetString("AfdelingKindVerplicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijd valt buiten afdelingsverdeling..
        /// </summary>
        public static string AfdelingNietBeschikbaar {
            get {
                return ResourceManager.GetString("AfdelingNietBeschikbaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geselecteerde afdeling bevat leden of leiding, en kan dus niet verwijderd worden..
        /// </summary>
        public static string AfdelingNietLeeg {
            get {
                return ResourceManager.GetString("AfdelingNietLeeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een afdeling met code &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        public static string AfdelingsCodeBestaatAl {
            get {
                return ResourceManager.GetString("AfdelingsCodeBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}-{2}.
        /// </summary>
        public static string AfdelingsLijstTitel {
            get {
                return ResourceManager.GetString("AfdelingsLijstTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon leden/leiding uit afdeling {0}.
        /// </summary>
        public static string AfdelingsLinkTitel {
            get {
                return ResourceManager.GetString("AfdelingsLinkTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een afdeling met die naam: &apos;{1}&apos; (&apos;{0}&apos;)..
        /// </summary>
        public static string AfdelingsNaamBestaatAl {
            get {
                return ResourceManager.GetString("AfdelingsNaamBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De opgegeven waarde voldoet niet aan de voorwaarden..
        /// </summary>
        public static string AlgemeneValidatieFout {
            get {
                return ResourceManager.GetString("AlgemeneValidatieFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet de contactpersoon en het adres nog invullen van je bivak &lt;a href=&apos;{1}&apos;&gt; {0} &lt;/a&gt;..
        /// </summary>
        public static string BeideNogInvullenOpBivakAangifte {
            get {
                return ResourceManager.GetString("BeideNogInvullenOpBivakAangifte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to België.
        /// </summary>
        public static string Belgie {
            get {
                return ResourceManager.GetString("Belgie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet je bivakaangifte nog &lt;a href=&apos;{0}&apos;&gt; invullen &lt;/a&gt;..
        /// </summary>
        public static string BivakAangifteNogInTeVullen {
            get {
                return ResourceManager.GetString("BivakAangifteNogInTeVullen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een categorie met code &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        public static string CategorieCodeBestaatAl {
            get {
                return ResourceManager.GetString("CategorieCodeBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat al een categorie met die naam: &apos;{1}&apos; (&apos;{0}&apos;)..
        /// </summary>
        public static string CategorieNaamBestaatAl {
            get {
                return ResourceManager.GetString("CategorieNaamBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om {0} contactpersoon te maken, moet je een van {1} e-mailadressen inschrijven voor de nieuwsbrief..
        /// </summary>
        public static string ContactMoetNieuwsBriefKrijgen {
            get {
                return ResourceManager.GetString("ContactMoetNieuwsBriefKrijgen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deelnemersinformatie {0} {1}.
        /// </summary>
        public static string DeelnemerBewerken {
            get {
                return ResourceManager.GetString("DeelnemerBewerken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De perso(o)n(en) werd(en) ingeschreven voor de uitstap &apos;{0}&apos;..
        /// </summary>
        public static string DeelnemersToegevoegdFeedback {
            get {
                return ResourceManager.GetString("DeelnemersToegevoegdFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geselecteerde deelnemer werd uitgeschreven.
        /// </summary>
        public static string DeelnemerUitgeschreven {
            get {
                return ResourceManager.GetString("DeelnemerUitgeschreven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} heeft geen e-mailadres. Om {1} contactpersoon te maken, moet je {1} een e-mailadres geven, en {1} met dat e-mailadres inschrijven voor de nieuwsbrief..
        /// </summary>
        public static string EmailVoorContactOntbreekt {
            get {
                return ResourceManager.GetString("EmailVoorContactOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres voor leiding verplicht..
        /// </summary>
        public static string EmailVoorLeidingOntbreekt {
            get {
                return ResourceManager.GetString("EmailVoorLeidingOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De waarde voor {0} voldoet niet aan de verplichte structuur: {1}.
        /// </summary>
        public static string FormatValidatieFout {
            get {
                return ResourceManager.GetString("FormatValidatieFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kon van deze persoon geen lid maken.  Misschien is er geen geschikte afdeling? Controleer eventueel de geboortedatum en/of Chiroleeftijd..
        /// </summary>
        public static string FoutToggleNaarKind {
            get {
                return ResourceManager.GetString("FoutToggleNaarKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kon van deze persoon geen leid(st)er maken.  Misschien is de persoon nog te jong? Controleer eventueel de geboortedatum en/of Chiroleeftijd..
        /// </summary>
        public static string FoutToggleNaarLeiding {
            get {
                return ResourceManager.GetString("FoutToggleNaarLeiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je groep heeft al een functie met code &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        public static string FunctieCodeBestaatAl {
            get {
                return ResourceManager.GetString("FunctieCodeBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn {2} ingeschreven personen met de functie {0} ({1}), en er mag er zo maar één zijn..
        /// </summary>
        public static string FunctieMeerdereKeren {
            get {
                return ResourceManager.GetString("FunctieMeerdereKeren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je groep heeft al een functie met die naam: &apos;{1}&apos; (&apos;{0}&apos;)..
        /// </summary>
        public static string FunctieNaamBestaatAl {
            get {
                return ResourceManager.GetString("FunctieNaamBestaatAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is nog niemand met de functie {0} ({1})..
        /// </summary>
        public static string FunctieOntbreekt {
            get {
                return ResourceManager.GetString("FunctieOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functies bewerken.
        /// </summary>
        public static string FunctiesBewerkenTitel {
            get {
                return ResourceManager.GetString("FunctiesBewerkenTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functies van {0}.
        /// </summary>
        public static string FunctiesVan {
            get {
                return ResourceManager.GetString("FunctiesVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn te veel leden met de functie {0} ({1}).  Huidig aantal: {2}, verplicht maximum: {3}..
        /// </summary>
        public static string FunctieTeVeel {
            get {
                return ResourceManager.GetString("FunctieTeVeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn te weinig ingeschreven personen met de functie {0} ({1}).  Huidig aantal: {2}, verplicht minimum: {3}..
        /// </summary>
        public static string FunctieTeWeinig {
            get {
                return ResourceManager.GetString("FunctieTeWeinig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum ontbreekt..
        /// </summary>
        public static string GeboorteDatumOntbreekt {
            get {
                return ResourceManager.GetString("GeboorteDatumOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersrechten.
        /// </summary>
        public static string GebruikersOverzicht {
            get {
                return ResourceManager.GetString("GebruikersOverzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen afdelingen geactiveerd voor dit werkjaar.  Pas eerst je &lt;a href=&apos;{0}&apos;&gt;afdelingsverdeling&lt;/a&gt; aan..
        /// </summary>
        public static string GeenActieveAfdelingen {
            get {
                return ResourceManager.GetString("GeenActieveAfdelingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog geen adres ingevuld voor je bivakplaats. .
        /// </summary>
        public static string GeenAdresVoorBivak {
            get {
                return ResourceManager.GetString("GeenAdresVoorBivak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog geen bivak geregistreerd voor dit werkjaar.
        /// </summary>
        public static string GeenBivak {
            get {
                return ResourceManager.GetString("GeenBivak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog geen categorieën, dus kun je er ook geen mensen in stoppen. Maak categorieën aan op het tabblad &apos;Groep&apos;..
        /// </summary>
        public static string GeenCategorieenFout {
            get {
                return ResourceManager.GetString("GeenCategorieenFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog geen contactpersoon aangeduid. .
        /// </summary>
        public static string GeenContactVoorBivak {
            get {
                return ResourceManager.GetString("GeenContactVoorBivak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog geen uitstappen geregistreerd waarvoor je deelnemers kunt inschrijven..
        /// </summary>
        public static string GeenUitstappenFout {
            get {
                return ResourceManager.GetString("GeenUitstappenFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets foutgelopen toen we de gegevens wilden opvragen..
        /// </summary>
        public static string GegevensOpvragenMisluktFout {
            get {
                return ResourceManager.GetString("GegevensOpvragenMisluktFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je groep is inactief..
        /// </summary>
        public static string GroepInactief {
            get {
                return ResourceManager.GetString("GroepInactief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het gegeven groepswerkjaar hoort niet bij de gegeven groeps..
        /// </summary>
        public static string GroepNietBijGroepsWerKjaar {
            get {
                return ResourceManager.GetString("GroepNietBijGroepsWerKjaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GroepPlaatsDefault {
            get {
                return ResourceManager.GetString("GroepPlaatsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groepsinstellingen.
        /// </summary>
        public static string GroepsInstellingenTitel {
            get {
                return ResourceManager.GetString("GroepsInstellingenTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog geen Chirogroep geselecteerd.
        /// </summary>
        public static string GroepsnaamDefault {
            get {
                return ResourceManager.GetString("GroepsnaamDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De persoon is nu ingeschreven in je groep.  Voor het einde van zijn/haar probeerperiode kan je hem/haar opnieuw uitschrijven zonder kosten..
        /// </summary>
        public static string IngeschrevenFeedback {
            get {
                return ResourceManager.GetString("IngeschrevenFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets foutgelopen, de persoon kon niet worden ingeschreven..
        /// </summary>
        public static string InschrijvenMisluktFout {
            get {
                return ResourceManager.GetString("InschrijvenMisluktFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingeschreven personen {0}-{1}.
        /// </summary>
        public static string LedenOverzicht {
            get {
                return ResourceManager.GetString("LedenOverzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geselecteerde leden werden uitgeschreven..
        /// </summary>
        public static string LedenUitgeschreven {
            get {
                return ResourceManager.GetString("LedenUitgeschreven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet het adres nog aanvullen van &lt;a href=&apos;{1}&apos;&gt;{0} ingeschreven personen&lt;/a&gt;..
        /// </summary>
        public static string LedenZonderAdres {
            get {
                return ResourceManager.GetString("LedenZonderAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet het telefoonnummer nog invoeren van &lt;a href=&apos;{1}&apos;&gt;{0} ingeschreven personen&lt;/a&gt;..
        /// </summary>
        public static string LedenZonderTelefoonNummer {
            get {
                return ResourceManager.GetString("LedenZonderTelefoonNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet het e-mailadres van &lt;a href=&apos;{1}&apos;&gt;{0} leid(st)ers&lt;/a&gt; nog invoeren..
        /// </summary>
        public static string LeidingZonderEmail {
            get {
                return ResourceManager.GetString("LeidingZonderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid is opnieuw op actief gezet..
        /// </summary>
        public static string LidActiefGemaakt {
            get {
                return ResourceManager.GetString("LidActiefGemaakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres is verplicht..
        /// </summary>
        public static string LidAdresOntbreekt {
            get {
                return ResourceManager.GetString("LidAdresOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inschrijvingsgegevens.
        /// </summary>
        public static string LidGegevens {
            get {
                return ResourceManager.GetString("LidGegevens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid is op non-actief gezet..
        /// </summary>
        public static string LidNonActiefGemaakt {
            get {
                return ResourceManager.GetString("LidNonActiefGemaakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was al ingeschreven..
        /// </summary>
        public static string LidWasAlIngeschreven {
            get {
                return ResourceManager.GetString("LidWasAlIngeschreven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle filters opheffen.
        /// </summary>
        public static string LijstAlles {
            get {
                return ResourceManager.GetString("LijstAlles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leiding zonder e-mailadres.
        /// </summary>
        public static string LijstLeidingZonderEmail {
            get {
                return ResourceManager.GetString("LijstLeidingZonderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingeschreven zonder adres.
        /// </summary>
        public static string LijstOntbrekendAdres {
            get {
                return ResourceManager.GetString("LijstOntbrekendAdres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingeschreven zonder telefoonnummer.
        /// </summary>
        public static string LijstOntbrekendTelefoonNummer {
            get {
                return ResourceManager.GetString("LijstOntbrekendTelefoonNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leden en leiding in instapperiode.
        /// </summary>
        public static string LijstProbeerLeden {
            get {
                return ResourceManager.GetString("LijstProbeerLeden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verjaardagslijst.
        /// </summary>
        public static string LijstVerjaardagen {
            get {
                return ResourceManager.GetString("LijstVerjaardagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je mag geen kleuters aansluiten bij de Chiro..
        /// </summary>
        public static string MinimumLeeftijd {
            get {
                return ResourceManager.GetString("MinimumLeeftijd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De personen zijn nu ingeschreven in je groep..
        /// </summary>
        public static string MultiIngeschrevenFeedback {
            get {
                return ResourceManager.GetString("MultiIngeschrevenFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets foutgelopen, niet alle personen konden worden ingeschreven..
        /// </summary>
        public static string MultiInschrijvenMisluktFout {
            get {
                return ResourceManager.GetString("MultiInschrijvenMisluktFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt nog niemand geselecteerd, dus kun je die actie niet uitvoeren.
        /// </summary>
        public static string NiemandGeselecteerdFout {
            get {
                return ResourceManager.GetString("NiemandGeselecteerdFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe afdeling.
        /// </summary>
        public static string NieuweAfdelingTitel {
            get {
                return ResourceManager.GetString("NieuweAfdelingTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe persoon.
        /// </summary>
        public static string NieuwePersoonTitel {
            get {
                return ResourceManager.GetString("NieuwePersoonTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe uitstap.
        /// </summary>
        public static string NieuweUitstap {
            get {
                return ResourceManager.GetString("NieuweUitstap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onbekend geslacht..
        /// </summary>
        public static string OnbekendGeslacht {
            get {
                return ResourceManager.GetString("OnbekendGeslacht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er bestaat zo geen actie om uit te voeren op een selectie personen..
        /// </summary>
        public static string OnbestaandeActieFeedback {
            get {
                return ResourceManager.GetString("OnbestaandeActieFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets mis met de geboortejaren. Staan ze overal in de juiste volgorde? Let er ook op dat je geen kleuters mag aansluiten bij de Chiro..
        /// </summary>
        public static string OngeldigeGeboorteJarenVoorAfdeling {
            get {
                return ResourceManager.GetString("OngeldigeGeboorteJarenVoorAfdeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onverwachte fout..
        /// </summary>
        public static string OnverwachteFout {
            get {
                return ResourceManager.GetString("OnverwachteFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overzicht.
        /// </summary>
        public static string Overzicht {
            get {
                return ResourceManager.GetString("Overzicht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen inschrijven.
        /// </summary>
        public static string PersonenInschrijven {
            get {
                return ResourceManager.GetString("PersonenInschrijven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet de contactpersoon nog invullen van je bivak &lt;a href=&apos;{1}&apos;&gt; {0} &lt;/a&gt;..
        /// </summary>
        public static string PersoonNogInvullenOpBivakAangifte {
            get {
                return ResourceManager.GetString("PersoonNogInvullenOpBivakAangifte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoon is overleden..
        /// </summary>
        public static string PersoonOverleden {
            get {
                return ResourceManager.GetString("PersoonOverleden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leden en leiding in probeerperiode.
        /// </summary>
        public static string ProbeerLeden {
            get {
                return ResourceManager.GetString("ProbeerLeden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is beperkt van {1} tot {2}..
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---/----.
        /// </summary>
        public static string StamNrDefault {
            get {
                return ResourceManager.GetString("StamNrDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer ontbreekt..
        /// </summary>
        public static string TelefoonNummerOntbreekt {
            get {
                return ResourceManager.GetString("TelefoonNummerOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijven voor uitstap/bivak.
        /// </summary>
        public static string UitstapInschrijving {
            get {
                return ResourceManager.GetString("UitstapInschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitstappen.
        /// </summary>
        public static string Uitstappen {
            get {
                return ResourceManager.GetString("Uitstappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De uitstap is verwijderd.
        /// </summary>
        public static string UitstapVerwijderd {
            get {
                return ResourceManager.GetString("UitstapVerwijderd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De uitstap kon niet verwijderd worden.
        /// </summary>
        public static string UitstapVerwijderenFout {
            get {
                return ResourceManager.GetString("UitstapVerwijderenFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je uitstap eindigt voor hij begint, heb je de data omgedraaid?.
        /// </summary>
        public static string VanTotUitstap {
            get {
                return ResourceManager.GetString("VanTotUitstap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets foutgegaan bij het laden van de volledige ledenlijst. Het nieuwe werkjaar is aangemaakt, maar er zijn nog geen leden overgezet.
        ///Je kunt dit nog steeds doen door onder &apos;leden&apos; te klikken op het vorige werkjaar. Daar selecteer je diegenen die opnieuw lid wilt maken, en kies je &apos;inschrijven&apos; onder &apos;acties&apos;..
        /// </summary>
        public static string VoorstelNieuweLedenMislukt {
            get {
                return ResourceManager.GetString("VoorstelNieuweLedenMislukt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sommige personen kunnen niet ingeschreven worden omdat hun gegevens niet volledig zijn. We vragen dat ieder lid een geboortedatum, adres en telefoonnummer heeft, en iedere leid(st)er ook een e-mailadres. Op die manier kunnen wij voor een goede dienstverlening zorgen..
        /// </summary>
        public static string WaaromWeLidgegevensVragen {
            get {
                return ResourceManager.GetString("WaaromWeLidgegevensVragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De &lt;a href=&apos;{2}&apos;&gt;overgang&lt;/a&gt; naar werkjaar {0}-{1} moet nog gebeuren..
        /// </summary>
        public static string WerkJaarInOvergang {
            get {
                return ResourceManager.GetString("WerkJaarInOvergang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets foutgelopen, de wijzigingen zijn niet opgeslagen.
        /// </summary>
        public static string WijzigingenNietOpgeslagenFout {
            get {
                return ResourceManager.GetString("WijzigingenNietOpgeslagenFout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De wijzigingen zijn opgeslagen.
        /// </summary>
        public static string WijzigingenOpgeslagenFeedback {
            get {
                return ResourceManager.GetString("WijzigingenOpgeslagenFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze persoon woont al op het gevraagde adres..
        /// </summary>
        public static string WoontDaarAl {
            get {
                return ResourceManager.GetString("WoontDaarAl", resourceCulture);
            }
        }
    }
}
