//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Chiro.Gap.WebApp.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("/Gav")]
        public string GroepKiezenUrl {
            get {
                return ((string)(this["GroepKiezenUrl"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("310")]
        public int TestGroepID {
            get {
                return ((int)(this["TestGroepID"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int AutoSuggestieStandaardLimiet {
            get {
                return ((int)(this["AutoSuggestieStandaardLimiet"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public int KleinAantalPersonen {
            get {
                return ((int)(this["KleinAantalPersonen"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("16")]
        public int LoonVerliesVanafLeeftijd {
            get {
                return ((int)(this["LoonVerliesVanafLeeftijd"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2.38")]
        public decimal PrijsVerzekeringLoonVerlies {
            get {
                return ((decimal)(this["PrijsVerzekeringLoonVerlies"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("C:\\Errors\\GAP-Foutlog.txt")]
        public string LogBestandPad {
            get {
                return ((string)(this["LogBestandPad"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("9")]
        public decimal PrijsAansluiting {
            get {
                return ((decimal)(this["PrijsAansluiting"]));
            }
        }
    }
}
