//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Gap.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Gap.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen toegang..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkel het nationaal secretariaat mag AD-nummers wijzigen..
        /// </summary>
        internal static string AdNummerNietWijzigen {
            get {
                return ResourceManager.GetString("AdNummerNietWijzigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het gevraagde adres is niet gekoppeld aan de gevraagde persoon..
        /// </summary>
        internal static string AdresNietGekoppeld {
            get {
                return ResourceManager.GetString("AdresNietGekoppeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was al als {1} ingeschreven..
        /// </summary>
        internal static string AlAndersIngeschreven {
            get {
                return ResourceManager.GetString("AlAndersIngeschreven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to België.
        /// </summary>
        internal static string Belgie {
            get {
                return ResourceManager.GetString("Belgie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een los te koppelen persoon zat niet in de gevraagde categorie..
        /// </summary>
        internal static string CategorieNietGekoppeld {
            get {
                return ResourceManager.GetString("CategorieNietGekoppeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De categorie is niet leeg..
        /// </summary>
        internal static string CategorieNietLeeg {
            get {
                return ResourceManager.GetString("CategorieNietLeeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een e-mailadres is verplicht.
        /// </summary>
        internal static string EmailOntbreekt {
            get {
                return ResourceManager.GetString("EmailOntbreekt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeerde een entiteit toe te voegen die al bestond..
        /// </summary>
        internal static string EntiteitBestondAl {
            get {
                return ResourceManager.GetString("EntiteitBestondAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is zo geen categorie in de gegeven groep..
        /// </summary>
        internal static string FouteCategorieVoorGroep {
            get {
                return ResourceManager.GetString("FouteCategorieVoorGroep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De communicatievorm behoort niet toe aan de geselecteerde persoon..
        /// </summary>
        internal static string FouteCommunicatieVormVoorPersoonString {
            get {
                return ResourceManager.GetString("FouteCommunicatieVormVoorPersoonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De groep van de uitstap verschilt van de groep van de deelnemer..
        /// </summary>
        internal static string FoutieveGroepUitstap {
            get {
                return ResourceManager.GetString("FoutieveGroepUitstap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen toegang..
        /// </summary>
        internal static string GeenGav {
            get {
                return ResourceManager.GetString("GeenGav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is nog geen werkjaar gemaakt voor deze groep..
        /// </summary>
        internal static string GeenWerkJaar {
            get {
                return ResourceManager.GetString("GeenWerkJaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was al uitgeschreven uit je groep..
        /// </summary>
        internal static string IsAlUitgeschreven {
            get {
                return ResourceManager.GetString("IsAlUitgeschreven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was is al ingeschreven in je groep..
        /// </summary>
        internal static string IsNogIngeschreven {
            get {
                return ResourceManager.GetString("IsNogIngeschreven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is nog niet ingeschreven in je groep..
        /// </summary>
        internal static string IsNogNietIngeschreven {
            get {
                return ResourceManager.GetString("IsNogNietIngeschreven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een kind moet in exact 1 afdeling zitten..
        /// </summary>
        internal static string KindInEenAfdelingsJaar {
            get {
                return ResourceManager.GetString("KindInEenAfdelingsJaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je mag geen nationale functies bewerken..
        /// </summary>
        internal static string NationaleFunctieNietBewerken {
            get {
                return ResourceManager.GetString("NationaleFunctieNietBewerken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit is niet mogelijk voor kaderploegen..
        /// </summary>
        internal static string NietVoorKader {
            get {
                return ResourceManager.GetString("NietVoorKader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je mag geen nationale functies bewerken.
        /// </summary>
        internal static string NationaleFunctieNietBewerken {
            get {
                return ResourceManager.GetString("NationaleFunctieNietBewerken", resourceCulture);
            }
        }
        
         /// <summary>
        ///   Looks up a localized string similar to Afdeling niet goed gedefinieerd in zijn werkjaar.
        /// </summary>
        internal static string OngeldigAfdelingsJaar {
            get {
                return ResourceManager.GetString("OngeldigAfdelingsJaar", resourceCulture);
            }
        }
       
        
        
        /// <summary>
        ///   Looks up a localized string similar to De naam van een categorie mag niet leeg zijn..
        /// </summary>
        internal static string OngeldigeCategorieNaam {
            get {
                return ResourceManager.GetString("OngeldigeCategorieNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Geboortejaar van&apos; mag niet groter zijn dan &apos;geboortejaar tot&apos;..
        /// </summary>
        internal static string OngeldigeGeborteJarenAfdelingsJaar {
            get {
                return ResourceManager.GetString("OngeldigeGeborteJarenAfdelingsJaar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldige groepsnaam..
        /// </summary>
        internal static string OngeldigeGroepsNaam {
            get {
                return ResourceManager.GetString("OngeldigeGroepsNaam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig lidtype..
        /// </summary>
        internal static string OngeldigLidType {
            get {
                return ResourceManager.GetString("OngeldigLidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeert een lid te koppelen aan een ongeldige afdeling..
        /// </summary>
        internal static string OngelidgeAfdelingVoorLid {
            get {
                return ResourceManager.GetString("OngelidgeAfdelingVoorLid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het is nog te vroeg op het werkjaar om een nieuw werkjaar te beginnen..
        /// </summary>
        internal static string OvergangTeVroeg {
            get {
                return ResourceManager.GetString("OvergangTeVroeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De rol {0} wordt nog niet ondersteund..
        /// </summary>
        internal static string RolNietOndersteund {
            get {
                return ResourceManager.GetString("RolNietOndersteund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was al leiding..
        /// </summary>
        internal static string WasAlLeiding {
            get {
                return ResourceManager.GetString("WasAlLeiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was al lid..
        /// </summary>
        internal static string WasAlLid {
            get {
                return ResourceManager.GetString("WasAlLid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je probeerde iemand te verhuizen naar een adres waar hij/zij al woont.
        /// </summary>
        internal static string WoontDaarAl {
            get {
                return ResourceManager.GetString("WoontDaarAl", resourceCulture);
            }
        }
    }
}
