//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Chiro.Gap.Services.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public int KleinAantal {
            get {
                return ((int)(this["KleinAantal"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("gaplive")]
        public string LiveConnSubstring {
            get {
                return ((string)(this["LiveConnSubstring"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public int LeidingVanafLeeftijd {
            get {
                return ((int)(this["LeidingVanafLeeftijd"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("bSzTnlw7aalstnLytquah4jAMbVrMK3lgViEqXT2WB0=")]
        public string EncryptieSleutel {
            get {
                return ((string)(this["EncryptieSleutel"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("FA/NSFrNPj3IPOsqsDLJgc2wVeeTHaktE0wkXtN5n3Q=")]
        public string HashSleutel {
            get {
                return ((string)(this["HashSleutel"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("http://test.ic-verzekeringen.be/chiro/logon.asp?user={0}&hash={1}")]
        public string UrlVerzekeraar {
            get {
                return ((string)(this["UrlVerzekeraar"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("20")]
        public int AantalStraatSuggesties {
            get {
                return ((int)(this["AantalStraatSuggesties"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("9")]
        public int NieuwWerkJaarMaand {
            get {
                return ((int)(this["NieuwWerkJaarMaand"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public int NieuwWerkJaarDag {
            get {
                return ((int)(this["NieuwWerkJaarDag"]));
            }
        }
    }
}
