--
------ eenmalige dingen...
----
----INSERT INTO pers.AdresType(AdresTypeID, Omschrijving)
----SELECT AdresTypeID, Omschrijving from KipAdmin.dbo.kipAdresType
--
--
--
---- BELANGRIJK! Eerst moeten de gegevens van CRAB overgezet worden!
--
--
--TRUNCATE TABLE pers.GelieerdePersoon;
--DELETE FROM pers.Persoon WHERE PersoonID > 0;
--DELETE FROM grp.Groep WHERE GroepID > 0;
--
--
--TRUNCATE TABLE adr.Adres;
--
--
--
----- GROEPEN OVERZETTEN
--
--INSERT INTO grp.Groep(Naam, Code, OprichtingsJaar, WebSite)
--SELECT
--  Naam
--, StamNr AS Code
--, Jr_Aanslui AS OprichtingsJaar
--, lower(HomePage) AS WebSite
--FROM KipAdmin.dbo.Groep g
--WHERE g.StamNr IN
--(
--  'MG /0313','OM /2107','MJ /0206','LEM/0109','LM /0707','AM /0311','MM /0408','WM /1501','MG /0111','WJ /1803'
--)
--
----- PERSONEN OVERZETTEN
--
--INSERT INTO pers.Persoon(AdNummer, Naam, VoorNaam, GeboorteDatum, Geslacht, ChiroLeefTijd)
--SELECT DISTINCT
--  p.AdNr AS AdNummer
--, p.Naam, p.VoorNaam, p.GeboorteDatum, p.Geslacht
--, 0 AS ChiroLeefTijd
--FROM KipAdmin.dbo.kipPersoon p
--JOIN KipadMin.dbo.kipLidLeidKad lk ON p.AdNr = lk.AdNr
--JOIN grp.Groep g ON lk.StamNr COLLATE SQL_Latin1_General_CP1_CI_AS = g.Code COLLATE SQL_Latin1_General_CP1_CI_AS
--
--
----- PERSONEN KOPPELEN AAN GROEPEN
--
--INSERT INTO pers.GelieerdePersoon
--SELECT DISTINCT g.GroepID, p.PersoonID
--FROM KipAdmin.dbo.kipLidLeidKad lk
--JOIN grp.Groep g ON lk.StamNr COLLATE SQL_Latin1_General_CP1_CI_AS = g.Code COLLATE SQL_Latin1_General_CP1_CI_AS
--JOIN pers.Persoon p ON lk.AdNr = p.AdNummer
--
--
--
----- ADRESSEN MATCHEN
--
--INSERT INTO adr.Adres (Bus,HuisNr,PostCode,StraatID,SubgemeenteID)
--SELECT distinct '' AS Bus, CAST(kipadmin.dbo.EnkelCijfers(ka.Nr) AS INT) as HuisNr, '' AS PostCode, s.StraatID, sg.SubgemeenteID FROM kipAdmin.dbo.kipAdres ka 
--JOIN adr.Straat s ON ka.Straat COLLATE SQL_Latin1_General_CP1_CI_AI = s.Naam AND ka.PostNr COLLATE SQL_Latin1_General_CP1_CI_AI = cast(s.PostNr as varchar(5))
--JOIN adr.Subgemeente sg ON Gemeente COLLATE SQL_Latin1_General_CP1_CI_AI = sg.Naam AND ka.PostNr COLLATE SQL_Latin1_General_CP1_CI_AI = cast(s.PostNr as varchar(5))
--JOIN kipAdmin.dbo.kipWoont kw ON kw.AdresId = ka.AdresId
--JOIN pers.Persoon p ON kw.AdNr = p.AdNummer
--
--
--
----- PERSONEN KOPPELEN AAN GEMATCHTE ADRESSEN
--
--
--INSERT INTO pers.PersoonsAdres(IsStandaard, Opmerking, PersoonId, AdresId, AdresTypeId)
--SELECT distinct
--  CASE WHEN kw.VolgNr = 1 THEN 1 ELSE 0 END AS IsStandaard
--  , '' AS OPmerking
--  , p.PersoonID as PersoonID
--  , a.AdresID as AdresID
--  , kw.AdresTypeID as AdresTypeID
--FROM kipAdmin.dbo.kipAdres ka 
--JOIN adr.Straat s ON ka.Straat COLLATE SQL_Latin1_General_CP1_CI_AI = s.Naam AND ka.PostNr COLLATE SQL_Latin1_General_CP1_CI_AI = cast(s.PostNr as varchar(5))
--JOIN adr.Subgemeente sg ON Gemeente COLLATE SQL_Latin1_General_CP1_CI_AI = sg.Naam AND ka.PostNr COLLATE SQL_Latin1_General_CP1_CI_AI = cast(s.PostNr as varchar(5))
--JOIN kipAdmin.dbo.kipWoont kw ON kw.AdresId = ka.AdresId
--JOIN pers.Persoon p ON kw.AdNr = p.AdNummer
--JOIN adr.Adres a ON a.StraatID = s.StraatID AND a.SubgemeenteID = sg.SubgemeenteID AND CAST(kipadmin.dbo.EnkelCijfers(ka.Nr) AS INT) = a.HuisNr
--
--
----- E-MAILADRESSEN EN TELEFOONNRS
--
--INSERT INTO pers.CommunicatieType(Omschrijving, CommunicatieTypeID)
--SELECT Omschrijving, ContactTypeId from kipadmin.dbo.kipContactType

--INSERT INTO pers.CommunicatieVorm(PersoonID, CommunicatieTypeID, Nummer, Voorkeur)
--SELECT p.PersoonID, ci.ContactTypeID, ci.Info, case VolgNr when 1 then 1 else 0 end as voorkeur
--FROM pers.Persoon p 
--JOIN kipadmin.dbo.kipContactInfo ci ON p.AdNummer = ci.AdNr


--
------- GROEPSWERKJAREN
--
--INSERT INTO grp.GroepsWerkJaar(GroepID, WerkJaar)
--SELECT g.GroepID, wj.WerkJaar
--FROM grp.Groep g, core.vHuidigWerkJaar wj
--
