<?xml version="1.0" encoding="utf-8"?>
<Database Name="ChiroGroep" Class="ChiroGroepClassesDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DEVSERVER;Initial Catalog=ChiroGroep;Integrated Security=True" SettingsObjectName="CgDal.Properties.Settings" SettingsPropertyName="ChiroGroepConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="pers.Persoon" Member="Persoons">
    <Type Name="Persoon">
      <Column Name="AdNummer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="VoorNaam" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="GeboorteDatum" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Geslacht" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChiroLeefTijd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SterfDatum" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PersoonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Versie" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Persoon_PersoonsAdres" Member="PersoonsAdres" ThisKey="PersoonID" OtherKey="PersoonID" Type="PersoonsAdres" />
      <Association Name="Persoon_GelieerdePersoon" Member="GelieerdePersoons" ThisKey="PersoonID" OtherKey="PersoonID" Type="GelieerdePersoon" />
    </Type>
  </Table>
  <Table Name="pers.PersoonsAdres" Member="PersoonsAdres">
    <Type Name="PersoonsAdres">
      <Column Name="IsStandaard" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Opmerking" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="PersoonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdresID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdresTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Versie" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Persoon_PersoonsAdres" Member="Persoon" ThisKey="PersoonID" OtherKey="PersoonID" Type="Persoon" IsForeignKey="true" />
      <Association Name="AdresType_PersoonsAdres" Member="AdresType" ThisKey="AdresTypeID" OtherKey="AdresTypeID" Type="AdresType" IsForeignKey="true" />
      <Association Name="Adres_PersoonsAdres" Member="Adres" ThisKey="AdresID" OtherKey="AdresID" Type="Adres" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="pers.AdresType" Member="AdresTypes">
    <Type Name="AdresType">
      <Column Name="Omschrijving" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="AdresTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AdresType_PersoonsAdres" Member="PersoonsAdres" ThisKey="AdresTypeID" OtherKey="AdresTypeID" Type="PersoonsAdres" />
    </Type>
  </Table>
  <Table Name="adr.Adres" Member="Adres">
    <Type Name="Adres">
      <Column Name="Bus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HuisNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AdresID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StraatID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubgemeenteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Adres_PersoonsAdres" Member="PersoonsAdres" ThisKey="AdresID" OtherKey="AdresID" Type="PersoonsAdres" />
    </Type>
  </Table>
  <Table Name="grp.Groep" Member="Groeps">
    <Type Name="Groep">
      <Column Name="Naam" Type="System.String" DbType="VarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="OprichtingsJaar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WebSite" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GroepID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Groep_GelieerdePersoon" Member="GelieerdePersoons" ThisKey="GroepID" OtherKey="GroepID" Type="GelieerdePersoon" />
    </Type>
  </Table>
  <Table Name="pers.GelieerdePersoon" Member="GelieerdePersoons">
    <Type Name="GelieerdePersoon">
      <Column Name="GroepID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersoonID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Groep_GelieerdePersoon" Member="Groep" ThisKey="GroepID" OtherKey="GroepID" Type="Groep" IsForeignKey="true" />
      <Association Name="Persoon_GelieerdePersoon" Member="Persoon" ThisKey="PersoonID" OtherKey="PersoonID" Type="Persoon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="pers.vPersoonsInfo" Member="vPersoonsInfos">
    <Type Name="vPersoonsInfo">
      <Column Name="PersoonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VoorNaam" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(160) NOT NULL" CanBeNull="false" />
      <Column Name="Categorieen" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StraatNaam" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="HuisNr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostNr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubGemeente" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="GeboorteDatum" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="EindeInstapPeriode" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NonActief" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TelefoonNummer" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(160)" CanBeNull="true" />
    </Type>
  </Table>
</Database>