-- OPGELET: de tabellen Straat en Subgemeente moeten al bestaan!
-- (zie ddl-adressen.sql)


--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 7.1.829
--   Created On : maandag, 16 juni, 2008 
--   DBMS       : SQL Server 2000 
--   -------------------------------------------------- 

USE ChiroGroep
GO

--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.FK_PersoonVrijVeldType_Groep') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonVrijVeldType DROP CONSTRAINT FK_PersoonVrijVeldType_Groep
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.FK_PersoonVrijVeldType_VrijVeldType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonVrijVeldType DROP CONSTRAINT FK_PersoonVrijVeldType_VrijVeldType
GO




IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.Persoon') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonVrijVeld DROP CONSTRAINT Persoon
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.PersoonVrijVeldType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonVrijVeld DROP CONSTRAINT PersoonVrijVeldType
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.Groep') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.GelieerdePersoon DROP CONSTRAINT Groep
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.Persoon') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.GelieerdePersoon DROP CONSTRAINT Persoon
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.FK_CommunicatieVorm_CommunicatieType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.CommunicatieVorm DROP CONSTRAINT FK_CommunicatieVorm_CommunicatieType
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.FK_CommunicatieVorm_Persoon') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.CommunicatieVorm DROP CONSTRAINT FK_CommunicatieVorm_Persoon
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.Persoon') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonsCategorie DROP CONSTRAINT Persoon
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.Categorie') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonsCategorie DROP CONSTRAINT Categorie
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.Persoon') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonsAdres DROP CONSTRAINT Persoon
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.Adres') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonsAdres DROP CONSTRAINT Adres
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('pers.FK_PersoonsAdres_AdresType') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE pers.PersoonsAdres DROP CONSTRAINT FK_PersoonsAdres_AdresType
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('grp.Adres') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE grp.GroepsAdres DROP CONSTRAINT Adres
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('grp.Groep') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE grp.GroepsAdres DROP CONSTRAINT Groep
GO


--  Drop Tables, Stored Procedures and Views 
IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('core.VrijVeldType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.VrijVeldType
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.PersoonVrijVeldType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.PersoonVrijVeldType
GO




IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.PersoonVrijVeld') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.PersoonVrijVeld
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.Persoon') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.Persoon
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.GelieerdePersoon') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.GelieerdePersoon
GO


IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('grp.Groep') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE grp.Groep
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.CommunicatieVorm') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.CommunicatieVorm
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.CommunicatieType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.CommunicatieType
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.PersoonsCategorie') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.PersoonsCategorie
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('core.Categorie') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE core.Categorie
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.AdresType') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.AdresType
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('pers.PersoonsAdres') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE pers.PersoonsAdres
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('grp.GroepsAdres') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE grp.GroepsAdres
GO

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('adr.Adres') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE adr.Adres
GO




--  Create Tables 
CREATE TABLE core.VrijVeldType ( 
	Naam varchar(80) NULL,
	DataType int NOT NULL,
	vrijVeldTypeID int NOT NULL
)
GO

CREATE TABLE pers.PersoonVrijVeldType ( 
	persoonVrijVeldTypeID int NOT NULL,
	groepID int NULL
)
GO




CREATE TABLE pers.PersoonVrijVeld ( 
	Waarde varchar(320) NULL,
	persoonID int NULL,
	persoonVrijVeldTypeID int NULL
)
GO

CREATE TABLE pers.Persoon ( 
	AdNummer int NULL,
	Naam varchar(160) NULL,
	VoorNaam varchar(60) NULL,
	GeboorteDatum smalldatetime NULL,
	Geslacht int NOT NULL,
	ChiroLeefTijd int DEFAULT 0 NOT NULL,    --  Dit veld geeft weer of een lid 'op zijn leeftijd' zit voor de automatische berekening van de afdeling.  Standaard heeft het de waarde 0.  Als een lid een jaartje hoger zit dan zijn/haar geboortedatum doet vermoeden (bijv. omdat hij/zij een leerjaar oversloeg) , dan zal dit veld op +1 staan. 
	SterfDatum smalldatetime NULL,
	Guid UniqueIdentifier NULL,
	persoonID int NOT NULL
)
GO

CREATE TABLE pers.GelieerdePersoon ( 
	groepID int NULL,
	persoonID int NULL
)
GO


CREATE TABLE grp.Groep ( 
	Naam varchar(160) NULL,
	Code char(10) NULL,    --  Voor een Chirogroep is de code het huidige stamnummer.  Als er ook gegevens van oud-leidingsploegen bewaard zullen worden op het nationaal secretariaat, zullen voor dit soort 'satellieten' ook codes bepaald moeten worden. 
	OprichtingsJaar int NULL,
	WebSite varchar(160) NULL,
	Logo image NULL,
	groepID int NOT NULL
)
GO

CREATE TABLE pers.CommunicatieVorm ( 
	Nota varchar(320) NULL,    --  'in het weekend', 'onder de werkuren', ... Interessant voor bijv. telefoonnummers. 
	Nummer varchar(160) NULL,    --  'nummer' is een misleidende naam, want het kan even goed gaan over een e-mailadres e.d. 
	CommunicatieVormID int IDENTITY(1,1) NOT NULL,
	CommunicatieTypeID int NULL,
	Voorkeur bit not NULL default 0,
	IsGezinsGebonden bit NOT NULL,    --  geeft aan of nummers/... van dit communicatietype gekopieerd moeten worden naar adresgenoten. 
	PersoonID int NULL
)
GO

CREATE TABLE pers.CommunicatieType ( 
	Omschrijving varchar(80) NULL,
	Validatie varchar(160) NULL,    --  Reguliere expressie die aangeeft hoe een geldig nummer/adres/... er uitziet 
	communicatieTypeID int NOT NULL
)
GO

CREATE TABLE pers.PersoonsCategorie ( 
	persoonID int NULL,	
	categorieID int NULL
)
GO

CREATE TABLE core.Categorie ( 
	Naam varchar(80) NULL,
	Code varchar(10) NULL,
	categorieID int IDENTITY(1,1) NOT NULL
)
GO

CREATE TABLE pers.AdresType ( 
	Omschrijving varchar(80) NULL,
	adresTypeID int NOT NULL
)
GO

CREATE TABLE pers.PersoonsAdres ( 
	IsStandaard bit NOT NULL,
	Opmerking text NULL,
	persoonID int NULL,
	adresID int NULL,
	adresTypeID int NULL
)
GO

CREATE TABLE grp.GroepsAdres ( 
	adresID int NULL,
	groepID int NULL
)
GO

CREATE TABLE adr.Adres ( 
	Bus varchar(10) NULL,
	HuisNr int NULL,
	PostCode varchar(10) NULL,    --  Niet te verwarren met postnummer.  Het postnummer is onlosmakelijk verbonden met de gemeente.  Het veld 'postcode' wordt gebruikt voor adressen in Nederland, waar er nog een niveau tussen adres en gemeente zit. 
	adresID int IDENTITY(1,1) NOT NULL
	StraatID int NOT NULL,
	SubgemeenteID int NOT NULL,
)
GO


--  Create Primary Key Constraints 
ALTER TABLE core.VrijVeldType ADD CONSTRAINT PK_VrijVeldType 
	PRIMARY KEY CLUSTERED (vrijVeldTypeID)
GO

ALTER TABLE pers.PersoonVrijVeldType ADD CONSTRAINT PK_PersoonVrijVeldType 
	PRIMARY KEY CLUSTERED (persoonVrijVeldTypeID)
GO

ALTER TABLE pers.Persoon ADD CONSTRAINT PK_Persoon 
	PRIMARY KEY CLUSTERED (persoonID)
GO

ALTER TABLE grp.Groep ADD CONSTRAINT PK_Groep 
	PRIMARY KEY CLUSTERED (groepID)
GO

ALTER TABLE pers.CommunicatieVorm ADD CONSTRAINT PK_CommunicatieVorm 
	PRIMARY KEY CLUSTERED (communicatieVormID)
GO

ALTER TABLE pers.CommunicatieType ADD CONSTRAINT PK_CommunicatieType 
	PRIMARY KEY CLUSTERED (communicatieTypeID)
GO

ALTER TABLE core.Categorie ADD CONSTRAINT PK_Categorie 
	PRIMARY KEY CLUSTERED (categorieID)
GO

ALTER TABLE pers.AdresType ADD CONSTRAINT PK_AdresType 
	PRIMARY KEY CLUSTERED (adresTypeID)
GO

ALTER TABLE adr.Adres ADD CONSTRAINT PK_Adres 
	PRIMARY KEY CLUSTERED (adresID)
GO




--  Create Foreign Key Constraints 
ALTER TABLE pers.PersoonVrijVeldType ADD CONSTRAINT FK_PersoonVrijVeldType_Groep 
	FOREIGN KEY (groepID) REFERENCES grp.Groep (groepID)
GO

ALTER TABLE pers.PersoonVrijVeldType ADD CONSTRAINT FK_PersoonVrijVeldType_VrijVeldType 
	FOREIGN KEY (persoonVrijVeldTypeID) REFERENCES core.VrijVeldType (vrijVeldTypeID)
GO




ALTER TABLE pers.PersoonVrijVeld ADD CONSTRAINT FK_PersoonVrijVeld_Persoon 
	FOREIGN KEY (persoonID) REFERENCES pers.Persoon (persoonID)
GO

ALTER TABLE pers.PersoonVrijVeld ADD CONSTRAINT FK_Persoon_PersoonVrijVeldType 
	FOREIGN KEY (persoonVrijVeldTypeID) REFERENCES pers.PersoonVrijVeldType (persoonVrijVeldTypeID)
GO

ALTER TABLE pers.GelieerdePersoon ADD CONSTRAINT FK_GelieerdePersoon_Groep 
	FOREIGN KEY (groepID) REFERENCES grp.Groep (groepID)
GO

ALTER TABLE pers.GelieerdePersoon ADD CONSTRAINT FK_GelieerdePersoon_Persoon 
	FOREIGN KEY (persoonID) REFERENCES pers.Persoon (persoonID)
GO

ALTER TABLE pers.CommunicatieVorm ADD CONSTRAINT FK_CommunicatieVorm_CommunicatieType 
	FOREIGN KEY (communicatieTypeID) REFERENCES pers.CommunicatieType (communicatieTypeID)
GO

ALTER TABLE pers.CommunicatieVorm ADD CONSTRAINT FK_CommunicatieVorm_Persoon 
	FOREIGN KEY (persoonID) REFERENCES pers.Persoon (persoonID)
GO

ALTER TABLE pers.PersoonsCategorie ADD CONSTRAINT FK_PersoonsCategorie_Persoon 
	FOREIGN KEY (persoonID) REFERENCES pers.Persoon (persoonID)
GO

ALTER TABLE pers.PersoonsCategorie ADD CONSTRAINT FK_PersoonsCategorie_Categorie 
	FOREIGN KEY (categorieID) REFERENCES core.Categorie (categorieID)
GO

ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT FK_PersoonsAdres_Persoon 
	FOREIGN KEY (persoonID) REFERENCES pers.Persoon (persoonID)
GO

ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT FK_PersoonsAdres_Adres 
	FOREIGN KEY (adresID) REFERENCES adr.Adres (adresID)
GO

ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT FK_PersoonsAdres_AdresType 
	FOREIGN KEY (adresTypeID) REFERENCES pers.AdresType (adresTypeID)
GO

ALTER TABLE grp.GroepsAdres ADD CONSTRAINT FK_GroepsAdres_Adres 
	FOREIGN KEY (adresID) REFERENCES adr.Adres (adresID)
GO

ALTER TABLE grp.GroepsAdres ADD CONSTRAINT FK_GroepsAdres_Groep 
	FOREIGN KEY (groepID) REFERENCES grp.Groep (groepID)
GO

ALTER TABLE [adr].[Adres]  WITH CHECK ADD  CONSTRAINT [FK_Adres_Straat] FOREIGN KEY([StraatID])
REFERENCES [adr].[Straat] ([StraatID])
GO
ALTER TABLE [adr].[Adres]  WITH CHECK ADD  CONSTRAINT [FK_Adres_Subgemeente] FOREIGN KEY([SubgemeenteID])
REFERENCES [adr].[Subgemeente] ([SubgemeenteID])









EXEC sp_addextendedproperty 'MS_Description', 'Deze klasse definieert omschrijft een vrij veld voor een persoon: wat is de naam van het veld, wat voor informatie kan het bevatten (getal, ja/nee, tekst,...)', 'User', pers, 'table', PersoonVrijVeldType
GO








EXEC sp_addextendedproperty 'MS_Description', 'Als een persoon met een ad-nummer in verschillende groepen gekend is, dan zullen we van deze persoon verschillende instanties maken.

Voordelen:
·	Een persoon kan in verschillende groepen een verschillend standaardadres hebben
·	Een dubbel ad-nummer veranderen is in eerste instantie niet moeilijk; enkel het veld ad-nummer moet gewijzigd worden bij personen die het foutieve ad-nummer hebben. (Records verwijderen is niet nodig)

(zie verslag 27/12/2007)', 'User', pers, 'table', Persoon
GO





EXEC sp_addextendedproperty 'MS_Description', 'Dit veld geeft weer of een lid ''op zijn leeftijd'' zit voor de automatische berekening van de afdeling.  Standaard heeft het de waarde 0.  Als een lid een jaartje hoger zit dan zijn/haar geboortedatum doet vermoeden (bijv. omdat hij/zij een leerjaar oversloeg) , dan zal dit veld op +1 staan.', 'User', pers, 'table', Persoon, 'column', ChiroLeefTijd
GO







EXEC sp_addextendedproperty 'MS_Description', 'Het programma wordt gebruikt voor de gegevens van 1 groep.  Meestal gaat het om een Chirogroep (gewesten en verbonden inc.).  Maar in de toekomst moet het programma ook gebruikt kunnen worden voor bijv. oud-leidingsploegen.', 'User', grp, 'table', Groep
GO

EXEC sp_addextendedproperty 'MS_Description', 'Voor een Chirogroep is de code het huidige stamnummer.  Als er ook gegevens van oud-leidingsploegen bewaard zullen worden op het nationaal secretariaat, zullen voor dit soort ''satellieten'' ook codes bepaald moeten worden.', 'User', grp, 'table', Groep, 'column', Code
GO





EXEC sp_addextendedproperty 'MS_Description', 'Een persoon kan een aantal communicatievormen hebben.  Een communicatievorm is bijvoorbeeld een telefoonnummer, faxnummer, gsm-nummer, e-mailadres, een login voor msn messenger of xmpp (jabber, google),...', 'User', pers, 'table', CommunicatieVorm
GO
EXEC sp_addextendedproperty 'MS_Description', '''in het weekend'', ''onder de werkuren'', ... Interessant voor bijv. telefoonnummers.', 'User', pers, 'table', CommunicatieVorm, 'column', Nota
GO

EXEC sp_addextendedproperty 'MS_Description', '''nummer'' is een misleidende naam, want het kan even goed gaan over een e-mailadres e.d.', 'User', pers, 'table', CommunicatieVorm, 'column', Nummer
GO




EXEC sp_addextendedproperty 'MS_Description', 'E-mail, vaste telefoon, gsm, I.M.,...', 'User', pers, 'table', CommunicatieType
GO

EXEC sp_addextendedproperty 'MS_Description', 'Reguliere expressie die aangeeft hoe een geldig nummer/adres/... er uitziet', 'User', pers, 'table', CommunicatieType, 'column', Validatie
GO

EXEC sp_addextendedproperty 'MS_Description', 'geeft aan of nummers/... van dit communicatietype gekopieerd moeten worden naar adresgenoten.', 'User', pers, 'table', CommunicatieType, 'column', IsGezinsGebonden
GO




EXEC sp_addextendedproperty 'MS_Description', 'Personen kunnen tot een categorie behoren.  Vergelijk het met het ''taggen'' van e-mailberichten.  Een categorie kan een aantal personen bevatten, en omgekeerd kan een persoon tot verschillende categorieen behoren.

De gebruiker van het programma kan zo veel categorieen maken als hij/zij wil.

Nuttige categorie: ''kandidaatlid''', 'User', core, 'table', Categorie
GO



EXEC sp_addextendedproperty 'MS_Description', 'Kotadres, thuisadres, bivakadres, werkadres,...', 'User', pers, 'table', AdresType
GO









EXEC sp_addextendedproperty 'MS_Description', 'Een adres is 1 geheel.  Het is mogelijk dat meerdere mensen hetzelfde adres hebben.  Een persoon kan anderzijds ook meer dan 1 adres hebben.', 'User', adr, 'table', Adres
GO


EXEC sp_addextendedproperty 'MS_Description', 'Niet te verwarren met postnummer.  Het postnummer is onlosmakelijk verbonden met de gemeente.  Het veld ''postcode'' wordt gebruikt voor adressen in Nederland, waar er nog een niveau tussen adres en gemeente zit.', 'User', adr, 'table', Adres, 'column', PostCode
GO


-- Achteraf toegevoegde kolommen

ALTER TABLE pers.Persoon ADD
	Versie timestamp NOT NULL
GO

ALTER TABLE	pers.PersoonsAdres ADD
	Versie timestamp NOT NULL
GO

