--use "Chirogroep.AdressenGedoe"
--go
--
--ALTER TABLE pers.PersoonsAdres ADD
--	PersoonID int NULL
--GO
--
--UPDATE pa
--SET pa.PersoonID = gp.PersoonID
--FROM pers.PersoonsAdres pa
--JOIN pers.GelieerdePersoon gp ON pa.GelieerdePersoonID = gp.GelieerdePersoonID
--GO

--BEGIN TRANSACTION
--GO
--ALTER TABLE pers.PersoonsAdres
--	DROP CONSTRAINT FK_PersoonsAdres_GelieerdePersoon
--GO
--COMMIT
--BEGIN TRANSACTION
--GO
--ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT
--	FK_PersoonsAdres_Persoon FOREIGN KEY
--	(
--	PersoonID
--	) REFERENCES pers.Persoon
--	(
--	PersoonID
--	) ON UPDATE  NO ACTION 
--	 ON DELETE  NO ACTION 
--	
--GO
--COMMIT

--BEGIN TRANSACTION
--GO
--ALTER TABLE pers.PersoonsAdres
--	DROP CONSTRAINT FK_PersoonsAdres_AdresType
--GO
--COMMIT
--BEGIN TRANSACTION
--GO
--ALTER TABLE pers.PersoonsAdres
--	DROP CONSTRAINT FK_PersoonsAdres_Persoon
--GO
--COMMIT
--BEGIN TRANSACTION
--GO
--ALTER TABLE pers.PersoonsAdres
--	DROP CONSTRAINT FK_PersoonsAdres_Adres
--GO
--COMMIT
--BEGIN TRANSACTION
--GO
--CREATE TABLE pers.Tmp_PersoonsAdres
--	(
--	Opmerking text NULL,
--	AdresID int NOT NULL,
--	AdresTypeID int NOT NULL,
--	Versie timestamp NOT NULL,
--	PersoonsAdresID int NOT NULL IDENTITY (1, 1),
--	PersoonID int NOT NULL
--	)  ON [PRIMARY]
--	 TEXTIMAGE_ON [PRIMARY]
--GO
--SET IDENTITY_INSERT pers.Tmp_PersoonsAdres ON
--GO
--IF EXISTS(SELECT * FROM pers.PersoonsAdres)
--	 EXEC('INSERT INTO pers.Tmp_PersoonsAdres (Opmerking, AdresID, AdresTypeID, PersoonsAdresID, PersoonID)
--		SELECT Opmerking, AdresID, AdresTypeID, PersoonsAdresID, PersoonID FROM pers.PersoonsAdres WITH (HOLDLOCK TABLOCKX)')
--GO
--SET IDENTITY_INSERT pers.Tmp_PersoonsAdres OFF
--GO
--DROP TABLE pers.PersoonsAdres
--GO
--EXECUTE sp_rename N'pers.Tmp_PersoonsAdres', N'PersoonsAdres', 'OBJECT' 
--GO
--ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT
--	PK_PersoonsAdres PRIMARY KEY CLUSTERED 
--	(
--	PersoonsAdresID
--	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--
--GO
--ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT
--	FK_PersoonsAdres_Adres FOREIGN KEY
--	(
--	AdresID
--	) REFERENCES adr.Adres
--	(
--	AdresID
--	) ON UPDATE  NO ACTION 
--	 ON DELETE  NO ACTION 
--	
--GO
--ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT
--	FK_PersoonsAdres_Persoon FOREIGN KEY
--	(
--	PersoonID
--	) REFERENCES pers.Persoon
--	(
--	PersoonID
--	) ON UPDATE  NO ACTION 
--	 ON DELETE  NO ACTION 
--	
--GO
--ALTER TABLE pers.PersoonsAdres ADD CONSTRAINT
--	FK_PersoonsAdres_AdresType FOREIGN KEY
--	(
--	AdresTypeID
--	) REFERENCES pers.AdresType
--	(
--	AdresTypeID
--	) ON UPDATE  NO ACTION 
--	 ON DELETE  NO ACTION 
--	
--GO
--COMMIT
--
