//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiro.Ad.Workers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chiro.Ad.Workers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dag {0}
        ///
        ///
        ///
        ///Er wordt momenteel een Chiro-account voor je aangemaakt. Binnen een kwartiertje zal hij op al onze services beschikbaar zijn.
        ///
        ///  
        ///
        ///Gebruikersnaam: {1}
        ///  
        ///Wachtwoord: {2}
        ///  
        ///E-mailadres: {3}
        ///
        ///
        ///
        ///Je kunt deze account gebruiken om aan te melden bij webtoepassingen van de Chiro, zoals het GAP (https://gap.chiro.be), de GAP-staging (https://develop.chiro.be:2000/staging) en de Chirosite (https://www.chiro.be/user).
        ///
        ///De accountinstellingen kun je wijzigen op https://login.chiro.be. We raden aan  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GapAccountInfoMail {
            get {
                return ResourceManager.GetString("GapAccountInfoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dag {0}
        ///
        ///
        ///
        ///Vanaf nu heb je met je Chirologin ook toegang tot GAP-staging, dat is een versie van het GAP om mee te spelen en te testen. De gegevens zijn een kopie van de echte, maar als je dingen wijzigt of toevoegt, dan wordt dat niet aangepast in de centrale Chirodatabank.
        ///
        ///
        ///
        ///Als je je login of wachtwoord niet meer kent, surf dan naar https://login.chiro.be. Klik daar op &apos;Nieuw wachtwoord&apos; en vul je mailadres in.
        ///
        ///
        ///
        ///Groeten
        ///
        ///De Chirohelpdesk (Helpdesk@chiro.be).
        /// </summary>
        internal static string GapRechtenInfoMail {
            get {
                return ResourceManager.GetString("GapRechtenInfoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MailNietVerstuurd {
            get {
                return ResourceManager.GetString("MailNietVerstuurd", resourceCulture);
            }
        }
    }
}
